<script setup>
import {computed,ref,onMounted,onBeforeUnmount} from 'vue'
import {onBeforeRouteLeave,onBeforeRouteUpdate} from 'vue-router'
import {Plus,Delete,Edit,Search,Refresh,Back} from '@element-plus/icons-vue'
import {ElMessage,ElMessageBox} from 'element-plus'
import PageHeader from '../components/PageHeader.vue'
import DataTableFrame from '../components/DataTableFrame.vue'
import FinanceCurrencySelect from '../components/FinanceCurrencySelect.vue'
import {usePrototypeData} from '../data/usePrototypeData.js'
import {useFinanceContext} from '../data/financeBasicContext.js'
import {canWriteModule} from '../data/accessControl.js'
import {financeRateDraft,financeRateRows,financeRateErrors,currencyName,rateDescription,validFinancePeriod,nextFinancePeriod} from '../domain/financeBasics.js'
const {state,saveFinanceRates,editFinanceRate,deleteFinanceRate}=usePrototypeData()
const captureContext=useFinanceContext(state)
const writable=computed(()=>canWriteModule('exchangeRates')),empty=()=>({sourceCurrency:'',targetCurrency:'',period:''}),pending=ref(empty()),applied=ref(empty()),queryError=ref('')
const rows=computed(()=>financeRateRows(state).filter(row=>Object.entries(applied.value).every(([key,value])=>!value||row[key]===value)))
function query(){queryError.value=pending.value.period&&!validFinancePeriod(pending.value.period)?'生效期间须为YYYY-MM':'';if(!queryError.value)applied.value={...pending.value}}
const creating=ref(false),editing=ref(false),editId=ref(''),drafts=ref([]),draft=ref(financeRateDraft()),initial=ref(''),failure=ref('')
const dirty=computed(()=>(creating.value||editing.value)&&JSON.stringify(creating.value?drafts.value:draft.value)!==initial.value)
const errors=computed(()=>editing.value?financeRateErrors(draft.value,state,editId.value):{})
const invalid=computed(()=>creating.value?drafts.value.some(row=>Object.keys(financeRateErrors(row,state)).length):Object.keys(errors.value).length)
function create(){drafts.value=[financeRateDraft()];initial.value=JSON.stringify(drafts.value);failure.value='';creating.value=true}
function edit(row){editId.value=row.id;draft.value=financeRateDraft(row);initial.value=JSON.stringify(draft.value);failure.value='';editing.value=true}
async function leave(){if(!dirty.value)return true;const current=captureContext();try{await ElMessageBox.confirm('放弃尚未保存的汇率？','放弃修改',{confirmButtonText:'放弃修改',cancelButtonText:'继续编辑'});return current()}catch{return false}}
async function close(done){if(!await leave())return;creating.value=false;editing.value=false;if(typeof done==='function')done()}
function save(){try{if(creating.value)saveFinanceRates(drafts.value);else editFinanceRate(editId.value,draft.value);creating.value=false;editing.value=false;ElMessage.success('保存成功')}catch(error){failure.value=error.message}}
async function remove(row){const current=captureContext(state.financeBasics.rates.find(item=>item.id===row.id));try{await ElMessageBox.confirm(`删除${row.period} ${row.sourceCurrency}→${row.targetCurrency}的汇率？`,'删除汇率',{confirmButtonText:'确认删除',cancelButtonText:'取消',type:'warning'});if(!current())return;deleteFinanceRate(row.id);ElMessage.success('汇率已删除')}catch(error){if(error instanceof Error)ElMessage.error(error.message)}}
const disabledDate=date=>`${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}`>nextFinancePeriod(state.financeBasics.currentPeriod)
onBeforeRouteLeave(leave);onBeforeRouteUpdate(leave)
const unload=e=>{if(dirty.value){e.preventDefault();e.returnValue=''}}
onMounted(()=>window.addEventListener('beforeunload',unload));onBeforeUnmount(()=>window.removeEventListener('beforeunload',unload))
</script>
<template><div class="module-view finance-rates">
  <PageHeader :title="creating?'新增即期汇率':'即期汇率维护'"><template #actions><el-button v-if="creating" :icon="Back" @click="close">返回列表</el-button><el-button v-else-if="writable" :icon="Plus" type="primary" @click="create">新增汇率</el-button></template></PageHeader>
  <template v-if="!creating"><el-form class="rate-query" label-position="top" @submit.prevent="query"><el-form-item label="原币代码"><FinanceCurrencySelect v-model="pending.sourceCurrency" label="查询原币代码"/></el-form-item><el-form-item label="目标币种代码"><FinanceCurrencySelect v-model="pending.targetCurrency" label="查询目标币种代码"/></el-form-item><el-form-item label="生效期间" :error="queryError"><el-input v-model="pending.period" aria-label="查询生效期间" placeholder="YYYY-MM"/></el-form-item><div><el-button :icon="Search" type="primary" native-type="submit">查询</el-button><el-button :icon="Refresh" @click="pending=empty();applied=empty();queryError=''">重置</el-button></div></el-form>
  <DataTableFrame :rows="rows"><template #default="{rows:pageRows}"><el-table :data="pageRows" aria-label="即期汇率列表"><el-table-column v-for="[key,label,width] in [['period','生效期间',110],['sourceCurrency','原币代码',110],['sourceName','原币名称',110],['targetCurrency','目标币种代码',130],['targetName','目标币种名称',140],['rate','直接汇率',130],['description','说明',230],['updatedBy','更新人',170],['updatedAt','更新时间',180],['status','状态',110]]" :key="key" :prop="key" :label="label" :min-width="width"/><el-table-column v-if="writable" label="操作" width="170" fixed="right"><template #default="{row}"><el-button :icon="Edit" link type="primary" :disabled="row.status!=='已生效'" @click="edit(row)">编辑</el-button><el-button :icon="Delete" link type="danger" :disabled="row.status!=='已生效'" @click="remove(row)">删除</el-button></template></el-table-column></el-table></template></DataTableFrame></template>
  <template v-else><el-alert v-if="failure" :title="failure" type="error" :closable="false"/><el-form label-position="top" @submit.prevent="save"><div v-for="(row,index) in drafts" :key="index" class="rate-row"><div class="rate-row-title"><h2>汇率 {{index+1}}</h2><el-button :icon="Delete" text :disabled="drafts.length===1" :aria-label="`删除汇率第${index+1}行`" @click="drafts.splice(index,1)"/></div><div class="rate-grid">
    <el-form-item label="生效期间" required :error="financeRateErrors(row,state).period"><el-date-picker v-model="row.period" type="month" value-format="YYYY-MM" :disabled-date="disabledDate" :aria-label="`第${index+1}行生效期间`"/></el-form-item>
    <el-form-item label="原币代码" required :error="financeRateErrors(row,state).sourceCurrency"><FinanceCurrencySelect v-model="row.sourceCurrency" :label="`第${index+1}行原币代码`"/></el-form-item><el-form-item label="原币名称"><el-input :model-value="currencyName(row.sourceCurrency)" readonly/></el-form-item>
    <el-form-item label="目标币种代码" required :error="financeRateErrors(row,state).targetCurrency"><FinanceCurrencySelect v-model="row.targetCurrency" target :label="`第${index+1}行目标币种代码`"/></el-form-item><el-form-item label="目标币种名称"><el-input :model-value="currencyName(row.targetCurrency)" readonly/></el-form-item><el-form-item label="直接汇率" required :error="financeRateErrors(row,state).rate"><el-input v-model="row.rate" inputmode="decimal" :aria-label="`第${index+1}行直接汇率`"/></el-form-item>
    </div><p>{{rateDescription(row)}}</p><el-alert v-if="financeRateErrors(row,state).duplicate" :title="financeRateErrors(row,state).duplicate" type="error" :closable="false"/></div><div class="rate-actions"><el-button :icon="Plus" @click="drafts.push(financeRateDraft())">新增一行</el-button><el-button type="primary" :disabled="!writable||invalid" native-type="submit">保存汇率</el-button></div></el-form></template>
  <el-dialog v-model="editing" title="编辑即期汇率" width="min(700px,96vw)" :close-on-click-modal="false" :before-close="close"><el-alert v-if="failure" :title="failure" type="error" :closable="false"/><el-form label-position="top" @submit.prevent="save"><div class="rate-grid"><el-form-item v-for="[key,label] in [['period','生效期间'],['sourceCurrency','原币代码'],['targetCurrency','目标币种代码']]" :key="key" :label="label"><el-input :model-value="draft[key]" readonly :aria-label="'编辑'+label"/></el-form-item><el-form-item label="原币名称"><el-input :model-value="currencyName(draft.sourceCurrency)" readonly/></el-form-item><el-form-item label="目标币种名称"><el-input :model-value="currencyName(draft.targetCurrency)" readonly/></el-form-item><el-form-item label="直接汇率" required :error="errors.rate"><el-input v-model="draft.rate" aria-label="编辑直接汇率" inputmode="decimal"/></el-form-item></div><p>{{rateDescription(draft)}}</p></el-form><template #footer><el-button @click="close">取消</el-button><el-button type="primary" :disabled="!writable||invalid" @click="save">确认保存</el-button></template></el-dialog>
</div></template>
<style scoped>.rate-query{display:flex;gap:16px;flex-wrap:wrap;align-items:end;margin:16px 0}.rate-query .el-form-item{width:210px;margin:0}.rate-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:4px 18px}.rate-grid :deep(.el-date-editor){width:100%}.rate-row{border-bottom:1px solid var(--border);padding:16px 0}.rate-row-title{display:flex;justify-content:space-between;align-items:center}h2{font-size:16px}.rate-actions{display:flex;justify-content:flex-end;gap:8px;margin:20px 0}p{min-height:20px;color:var(--muted)}@media(max-width:700px){.rate-grid{grid-template-columns:minmax(0,1fr)}.rate-query .el-form-item{width:100%}}</style>
