<script setup>
import {computed,ref,nextTick,onMounted,onBeforeUnmount} from 'vue'
import {onBeforeRouteLeave} from 'vue-router'
import {Plus,Edit,Delete,Search,Refresh,Back} from '@element-plus/icons-vue'
import {ElMessage,ElMessageBox} from 'element-plus'
import PageHeader from '../components/PageHeader.vue'
import DataTableFrame from '../components/DataTableFrame.vue'
import {usePrototypeData} from '../data/usePrototypeData.js'
import {useFinanceContext} from '../data/financeBasicContext.js'
import {canWriteModule} from '../data/accessControl.js'
import {INVOICE_UNIT_FIELDS,invoiceUnitDraft,invoiceUnitErrors,invoiceProfileRows} from '../domain/financeBasics.js'
const {state,saveInvoiceUnit,deleteInvoiceUnit}=usePrototypeData(),writable=computed(()=>canWriteModule('invoiceEntities'))
const captureContext=useFinanceContext(state)
const empty=()=>({customerName:'',creditCode:''}),pending=ref(empty()),applied=ref(empty())
const rows=computed(()=>invoiceProfileRows(state).filter(row=>Object.entries(applied.value).every(([key,value])=>!value||row[key].includes(value))))
const profileId=ref(''),creating=ref(false),editing=ref(false),unitId=ref(''),draft=ref(invoiceUnitDraft()),root=ref({}),initial=ref(''),failure=ref(''),editor=ref(null)
const profile=computed(()=>invoiceProfileRows(state).find(row=>row.id===profileId.value)),units=computed(()=>state.financeBasics.invoiceUnits.filter(row=>row.profileId===profileId.value&&!row.deleted))
const customers=computed(()=>state.partners.filter(row=>row.type==='客户'&&row.status!=='已删除'))
const customer=computed(()=>customers.value.find(row=>row.id===root.value.partnerId))
const errors=computed(()=>invoiceUnitErrors(draft.value,state,profileId.value,unitId.value)),dirty=computed(()=>(creating.value||editing.value)&&initial.value!==JSON.stringify(creating.value?root.value:draft.value))
async function leave(){if(!dirty.value)return true;const current=captureContext();try{await ElMessageBox.confirm('放弃尚未保存的开票资料？','放弃修改',{confirmButtonText:'放弃修改',cancelButtonText:'继续编辑'});return current()}catch{return false}}
async function back(){if(!await leave())return;if(editing.value){editing.value=false;return}creating.value=false;profileId.value=''}
function create(){root.value={partnerId:'',customerCreditCode:'',companyCreditCode:'',...invoiceUnitDraft()};initial.value=JSON.stringify(root.value);failure.value='';creating.value=true}
function customerChanged(){root.value.customerCreditCode=customer.value?.creditCode||''}
async function editUnit(row){if(!await leave())return;unitId.value=row?.id||'';draft.value=invoiceUnitDraft(row);initial.value=JSON.stringify(draft.value);failure.value='';editing.value=true;await nextTick();editor.value?.scrollIntoView({block:'nearest'});editor.value?.querySelector('input')?.focus({preventScroll:true})}
function save(){try{saveInvoiceUnit(profileId.value,unitId.value,draft.value);editing.value=false;ElMessage.success('开票单位已保存')}catch(error){failure.value=error.message}}
async function remove(row){if(!await leave())return;const current=captureContext(row),owner=profileId.value;try{await ElMessageBox.confirm(`删除开票单位“${row.name}”？`,'删除开票单位',{confirmButtonText:'确认删除',cancelButtonText:'取消',type:'warning'});if(!current()||owner!==profileId.value)return;deleteInvoiceUnit(owner,row.id);editing.value=false;ElMessage.success('开票单位已删除')}catch(error){if(error instanceof Error)ElMessage.error(error.message)}}
onBeforeRouteLeave(leave)
const unload=e=>{if(dirty.value){e.preventDefault();e.returnValue=''}}
onMounted(()=>window.addEventListener('beforeunload',unload));onBeforeUnmount(()=>window.removeEventListener('beforeunload',unload))
</script>
<template><div class="module-view invoice-entities">
  <PageHeader :title="creating?'新增客户开票资料':profile?'客户开票单位明细维护':'客户开票单位维护'"><template #actions><el-button v-if="creating||profile" :icon="Back" @click="back">{{editing?'取消修改':'返回列表'}}</el-button><el-button v-if="writable&&!creating&&!editing" :icon="Plus" type="primary" @click="profile?editUnit():create()">{{profile?'新增开票单位':'新增客户开票资料'}}</el-button></template></PageHeader>
  <template v-if="!creating&&!profile"><el-form class="invoice-query" label-position="top" @submit.prevent="applied={...pending}"><el-form-item label="客户名称"><el-input v-model="pending.customerName" clearable aria-label="查询客户名称"/></el-form-item><el-form-item label="统一社会信用码"><el-input v-model="pending.creditCode" clearable aria-label="查询统一社会信用码"/></el-form-item><div><el-button :icon="Search" type="primary" native-type="submit">查询</el-button><el-button :icon="Refresh" @click="pending=empty();applied=empty()">重置</el-button></div></el-form>
  <DataTableFrame :rows="rows"><template #default="{rows:pageRows}"><el-table :data="pageRows" aria-label="客户开票资料列表"><el-table-column v-for="[key,label,width] in [['customerName','客户名称',200],['creditCode','统一社会信用码',210],['updatedBy','更新人',170],['updatedAt','更新时间',180],['status','状态',110]]" :key="key" :prop="key" :label="label" :min-width="width"/><el-table-column label="操作" :width="writable?165:100" fixed="right"><template #default="{row}"><el-button link type="primary" :icon="Edit" @click="profileId=row.id">{{writable?'编辑':'详情'}}</el-button><el-tooltip v-if="writable" content="客户级删除的级联和引用处理待确认（183）"><span><el-button link :icon="Delete" disabled>删除</el-button></span></el-tooltip></template></el-table-column></el-table></template></DataTableFrame></template>
  <template v-else-if="creating"><el-alert title="新增资料的客户信用码与开票公司信用码映射、银行联系字段必填性及初始状态待确认（181、182、183），暂不保存。" type="warning" :closable="false"/><el-form label-position="top"><div class="invoice-grid">
    <el-form-item label="客户名称" required><el-select v-model="root.partnerId" filterable aria-label="开票客户名称" @change="customerChanged"><el-option v-for="row in customers" :key="row.id" :value="row.id" :label="row.name"/></el-select></el-form-item>
    <el-form-item label="客户统一社会信用码" required><el-input v-model="root.customerCreditCode" :readonly="!!customer?.creditCode" maxlength="18" aria-label="客户统一社会信用码"/></el-form-item>
    <el-form-item label="开票公司统一社会信用码" required><el-input v-model="root.companyCreditCode" maxlength="18" aria-label="开票公司统一社会信用码"/></el-form-item>
    <el-form-item v-for="field in INVOICE_UNIT_FIELDS.filter(item=>item.key!=='taxpayerId')" :key="field.key" :label="field.label" :required="field.required"><el-radio-group v-if="field.key==='isDefault'" v-model="root.isDefault" aria-label="是否默认"><el-radio value="是">是</el-radio><el-radio value="否">否</el-radio></el-radio-group><el-input v-else v-model="root[field.key]" :maxlength="field.max" :aria-label="field.label"/></el-form-item>
  </div><div class="invoice-actions"><el-button @click="back">取消</el-button><el-button type="primary" disabled>保存 · 待确认</el-button></div></el-form></template>
  <template v-else><dl class="invoice-summary"><div><dt>客户名称</dt><dd>{{profile.customerName}}</dd></div><div><dt>统一社会信用码</dt><dd>{{profile.creditCode}}</dd></div><div><dt>状态</dt><dd>{{profile.status}}</dd></div></dl>
  <DataTableFrame :rows="units"><template #default="{rows:pageRows}"><el-table :data="pageRows" aria-label="开票单位明细"><el-table-column v-for="field in INVOICE_UNIT_FIELDS" :key="field.key" :prop="field.key" :label="field.label" :min-width="field.key==='isDefault'?100:field.key==='name'?230:190"/><el-table-column prop="updatedBy" label="更新人" width="170"/><el-table-column prop="updatedAt" label="更新时间" width="180"/><el-table-column v-if="writable" label="操作" width="170" fixed="right"><template #default="{row}"><el-button link type="primary" :icon="Edit" @click="editUnit(row)">调整</el-button><el-button link type="danger" :icon="Delete" @click="remove(row)">删除</el-button></template></el-table-column></el-table></template></DataTableFrame>
  <section v-if="editing" ref="editor" class="invoice-editor" aria-label="开票单位编辑"><h2>{{unitId?'调整开票单位':'新增开票单位'}}</h2><el-alert v-if="failure" :title="failure" type="error" :closable="false"/><el-form label-position="top" @submit.prevent="save"><div class="invoice-grid"><el-form-item v-for="field in INVOICE_UNIT_FIELDS" :key="field.key" :label="field.label" :required="field.required" :error="errors[field.key]"><el-radio-group v-if="field.key==='isDefault'" v-model="draft.isDefault" aria-label="明细是否默认"><el-radio value="是">是</el-radio><el-radio value="否">否</el-radio></el-radio-group><el-input v-else v-model="draft[field.key]" :maxlength="field.max" :aria-label="'明细'+field.label"/></el-form-item></div><div class="invoice-actions"><el-button @click="back">取消修改</el-button><el-button type="primary" :disabled="!writable||Object.keys(errors).length>0" native-type="submit">保存开票单位</el-button></div></el-form></section>
  </template>
</div></template>
<style scoped>.invoice-query{display:flex;gap:16px;flex-wrap:wrap;align-items:end;margin:16px 0}.invoice-query .el-form-item{width:260px;margin:0}.invoice-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:4px 18px}.invoice-summary{display:flex;flex-wrap:wrap;gap:20px 40px;margin:16px 0 24px}.invoice-summary dt{font-size:12px;color:var(--muted)}.invoice-summary dd{margin:6px 0 0}.invoice-actions{display:flex;justify-content:flex-end;gap:8px}.invoice-editor{border-top:1px solid var(--border);margin-top:24px;padding:20px 0}.invoice-editor h2{font-size:16px;margin:0 0 16px}.el-alert{margin:16px 0}.invoice-grid :deep(.el-form-item){min-width:0}@media(max-width:800px){.invoice-grid{grid-template-columns:repeat(2,minmax(0,1fr))}}@media(max-width:600px){.invoice-grid{grid-template-columns:minmax(0,1fr)}.invoice-query .el-form-item{width:100%}}</style>
