<script setup>
import {computed,ref,watch} from 'vue'
import {useRoute,useRouter} from 'vue-router'
import {useDraftNavigation} from '../utils/useDraftNavigation.js'
import {FINANCE_BASIC_ACCOUNTS} from '../domain/financeBasicAccess.js'
import {Back,Plus,Check,Download} from '@element-plus/icons-vue'
import {ElMessage,ElMessageBox} from 'element-plus'
import PageHeader from '../components/PageHeader.vue'
import RecordQueryTable from '../components/RecordQueryTable.vue'
import OrderCostFacts from '../components/finance/OrderCostFacts.vue'
import {usePrototypeData} from '../data/usePrototypeData.js'
import {canReadModule,canWriteModule,workbenchSession,accessState} from '../data/accessControl.js'
import {INVOICE_HEAD,INVOICE_LINES,TAX_INVOICES,GOODS_COLUMNS,PARTY_COLUMNS,invoiceSources,invoicePreview,backfillCandidates,backfillError} from '../domain/invoices.js'
import {displayValue} from '../domain/recordQuery.js'
import {downloadRecords} from '../utils/recordDownloads.js'
const data=usePrototypeData(),{state}=data,route=useRoute(),router=useRouter(),selected=ref(null),draft=ref(null),invoiceId=ref(''),buyerId=ref(''),bankId=ref(''),busy=ref(false)
const tab=computed(()=>['pending','backfill','tax'].includes(route.query.tab)?route.query.tab:'applications'),readable=computed(()=>canReadModule('invoices'))
const sourceRows=computed(()=>!readable.value?[]:tab.value==='pending'?invoiceSources(state):tab.value==='tax'?state.invoicing.taxInvoices:state.invoicing.applications.filter(row=>!row.deleted&&row.需要开票===(tab.value==='backfill'?'否':'是')).toSorted((a,b)=>b.开票申请号.localeCompare(a.开票申请号)))
const rows=computed(()=>sourceRows.value.filter(row=>workbenchSession.personaId==='superAdmin'||(row.companyId&&row.companyId===FINANCE_BASIC_ACCOUNTS[workbenchSession.personaId]?.companyId)))
const columns=computed(()=>tab.value==='pending'?INVOICE_LINES.filter(([key])=>!['即期汇率','本次开票金额(原币)','本次开票金额(人民币)'].includes(key)):tab.value==='tax'?TAX_INVOICES:INVOICE_HEAD)
const filters=computed(()=>tab.value==='pending'?[['对账单号','对账单号'],['订单号','订单号'],['客户','客户'],['结算单位','结算单位'],['提单号','提单号'],['币种','原币币种','select',['CNY','USD','HKD']],['对账单创建人','创建人'],['min','待开票金额从','min',null,'可开票金额(原币)'],['max','待开票金额至','max',null,'可开票金额(原币)'],['业务日期','业务日期','range'],['对账单确认日期','对账单确认日期','range']]:tab.value==='tax'?[['发票号码','发票号码'],['结算单位','结算单位'],['购买方','购买方'],['纳税识别号','纳税识别号'],['发票类型','发票类型'],['开票日期','开票日期','range'],['作废','发票是否作废','select',['是','否']],['min','合计金额从','min',null,'价税合计'],['max','合计金额至','max',null,'价税合计'],['minTax','税额从','min',null,'税额'],['maxTax','税额至','max',null,'税额']]:[['开票申请号','开票申请号'],['结算单位','结算单位'],['购买方','购买方'],['纳税识别号','纳税识别号'],['状态','状态','select',tab.value==='backfill'?['新建','已补录']:['新建','已提交','已开票']],['原币币种','原币币种','select',['CNY','USD','HKD']],['创建人','创建人'],['创建日期','创建日期','range'],['min','申请金额(原币)从','min',null,'申请金额(原币)'],['max','申请金额(原币)至','max',null,'申请金额(原币)'],['minLocal','申请金额(本位币)从','min',null,'申请金额(本位币)'],['maxLocal','申请金额(本位币)至','max',null,'申请金额(本位币)']])
const active=computed(()=>draft.value||selected.value),candidates=computed(()=>selected.value?backfillCandidates(state,selected.value):[]),picked=computed(()=>candidates.value.find(row=>row.id===invoiceId.value))
const face=computed(()=>picked.value||active.value),writable=computed(()=>workbenchSession.personaId==='financeAccountant'&&canWriteModule('invoices'))
const buyers=computed(()=>state.financeBasics.invoiceUnits.filter(unit=>!unit.deleted&&state.financeBasics.invoiceProfiles.some(profile=>profile.id===unit.profileId&&profile.partnerId===draft.value?.partyId&&profile.status==='已生效')))
const banks=computed(()=>state.financeBasics.bankAccounts.filter(bank=>bank.companyId===draft.value?.companyId&&bank.status==='已生效'))
function buyer(){const row=buyers.value.find(row=>row.id===buyerId.value);draft.value.buyer=row?{名称:row.name,纳税人识别号:row.taxpayerId,地址:row.address,电话:row.phone,开户行名称:row.bankName,银行账号:row.accountNo}:null}
function bank(){const row=banks.value.find(row=>row.id===bankId.value);draft.value.seller=row?{名称:'合成公司甲',纳税人识别号:'DEMOSELLER0000001',地址:'合成销售地址',电话:'00000000000',开户行名称:row.bankName,银行账号:row.accountNo}:null}
function create(records){try{draft.value=invoicePreview(records);buyerId.value='';bankId.value=''}catch(error){ElMessage.error(error.message)}}
async function leave(){if(!draft.value&&!invoiceId.value)return true;try{await ElMessageBox.confirm('放弃尚未保存的开票录入？','放弃修改',{confirmButtonText:'确认',cancelButtonText:'取消'});draft.value=null;invoiceId.value='';return true}catch{return false}}
useDraftNavigation(()=>!!draft.value||!!invoiceId.value,leave,()=>{selected.value=null})
async function navigate(next=tab.value){if(!await leave())return;selected.value=null;router.push({path:'/finance/invoices',query:{tab:next}})}
async function backfill(){if(busy.value)return;const error=backfillError(selected.value,picked.value);if(error)return ElMessage.error(error);const id=selected.value.id,invoice=invoiceId.value,context=JSON.stringify([workbenchSession.personaId,accessState.revision,state.invoicing]);busy.value=true;try{await ElMessageBox.confirm(`将 ${picked.value.发票号码} 关联至 ${selected.value.开票申请号}？`,'补录确认',{confirmButtonText:'确认',cancelButtonText:'取消'});if(context!==JSON.stringify([workbenchSession.personaId,accessState.revision,state.invoicing]))throw new Error('数据或角色已变化，请重新操作');data.backfillInvoice(id,invoice);invoiceId.value='';ElMessage.success('销项发票已补录')}catch(error){if(error instanceof Error)ElMessage.error(error.message)}finally{busy.value=false}}
watch(()=>[workbenchSession.personaId,accessState.revision,state.invoicing],()=>{draft.value=null;selected.value=null;invoiceId.value='';busy.value=false})
function goodsValue(row,key){const gross=Number(row['金额(含税)']),count=Number(row.数量),rate=Number(row['税率(%)']);if(key==='单价(含税)')return count>0?gross/count:'未计算';if(key==='税额')return Number.isFinite(gross)&&row['税率(%)']!==''?gross*rate/(100+rate):'未计算';return displayValue(row[key])}
</script>

<template>
  <div class="module-view invoice-view"><PageHeader :title="draft?'销项开票录入预览':selected?'销项发票详情':'销项发票'"><template #actions><el-button v-if="active" :icon="Back" @click="navigate()">返回列表</el-button></template></PageHeader><el-empty v-if="!readable" description="当前岗位未获销项发票查看授权"/>
    <template v-else><el-alert title="开票余额与票面映射待确认（214、215）；不连接百望。仅开放条件一致的 CNY 发票补录。" type="warning" :closable="false"/>
      <template v-if="!active"><el-tabs :model-value="tab" @update:model-value="navigate($event)"><el-tab-pane label="开票申请" name="applications"/><el-tab-pane label="待开票明细" name="pending"/><el-tab-pane label="销项发票补录" name="backfill"/><el-tab-pane label="税务发票" name="tax"/></el-tabs><RecordQueryTable :key="`${tab}:${workbenchSession.personaId}:${accessState.revision}`" :rows="rows" :columns="columns" :filters="filters" :name="`销项发票${tab}`" :page-size="10" :selectable="tab==='pending'" :detail="tab!=='pending'" :exportable="false" @detail="selected=$event"><template #actions="{rows:filtered,selection}"><template v-if="tab==='pending'"><el-button :icon="Plus" :disabled="!selection.length" @click="create(selection)">按勾选录入</el-button><el-button :icon="Plus" :disabled="!filtered.length" @click="create(filtered)">按查询条件录入</el-button></template></template></RecordQueryTable></template>
      <template v-else><el-alert v-if="active.demoOnly" title="合成票据样本，不占用对账金额，不具有税务效力。" type="info" :closable="false"/><OrderCostFacts :entries="INVOICE_HEAD.map(([key,label])=>[label,displayValue(active[key])])"/>
        <el-form v-if="draft" label-position="top" class="invoice-form"><el-form-item label="需要开票"><el-radio-group v-model="draft.需要开票" aria-label="需要开票"><el-radio-button value="是"/><el-radio-button value="否"/></el-radio-group></el-form-item><el-form-item label="即期汇率" required><el-input v-model="draft.即期汇率" aria-label="开票即期汇率"/></el-form-item></el-form>
        <section v-if="tab==='backfill'&&selected?.状态==='新建'"><h2>补录税务发票</h2><el-select v-model="invoiceId" clearable filterable aria-label="补录发票号" :disabled="!writable||busy"><el-option v-for="item in candidates" :key="item.id" :value="item.id" :label="item.发票号码"/></el-select><el-button :icon="Check" type="primary" :disabled="!writable||!picked||busy||!!backfillError(selected,picked)" @click="backfill">提交补录</el-button></section>
        <template v-if="!draft||draft.需要开票==='是'"><section><h2>票面购货单位</h2><el-select v-if="draft" v-model="buyerId" aria-label="购买方名称" @change="buyer"><el-option v-for="item in buyers" :key="item.id" :value="item.id" :label="item.name"/></el-select><OrderCostFacts :entries="PARTY_COLUMNS.map(([key,label])=>[label,displayValue(face.buyer?.[key])])"/></section><section><h2>票面销售单位</h2><el-select v-if="draft" v-model="bankId" aria-label="销售单位开户行" @change="bank"><el-option v-for="item in banks" :key="item.id" :value="item.id" :label="`${item.bankName} ${item.accountNo}`"/></el-select><OrderCostFacts :entries="PARTY_COLUMNS.map(([key,label])=>[label,displayValue(face.seller?.[key])])"/></section>
        <section><h2>货物及服务信息</h2><RecordQueryTable :rows="face.goods" :columns="GOODS_COLUMNS" name="票面货物与服务" :exportable="false"><template #actions><el-button v-if="draft" :icon="Plus" @click="draft.goods.push({id:`G-${draft.goods.length+1}`,货物或应税劳务名称:'',规格型号:'',单位:'',数量:'', '金额(含税)':'','税率(%)':''})">新建开票行</el-button></template><template #cell="{row,field}"><el-select v-if="draft&&field==='税率(%)'" v-model="row[field]" :aria-label="`税率 ${row.id}`"><el-option v-for="rate in [0,1,3,6,9,11]" :key="rate" :value="rate" :label="String(rate)"/></el-select><el-select v-else-if="draft&&field==='货物或应税劳务名称'" v-model="row[field]" :aria-label="`货物或应税劳务名称 ${row.id}`"><el-option label="合成物流服务" value="合成物流服务"/></el-select><el-input v-else-if="draft&&!['单价(含税)','税额'].includes(field)" v-model="row[field]" :aria-label="`${field} ${row.id}`"/><template v-else>{{draft?goodsValue(row,field):displayValue(row[field])}}</template></template></RecordQueryTable></section>
        <section><h2>其他开票信息</h2><el-form v-if="draft" label-position="top" class="invoice-form"><el-form-item v-for="field in ['收件人','复核人']" :key="field" :label="field"><el-select v-model="draft[field]" :aria-label="field"><el-option label="财务会计演示员" value="财务会计演示员"/></el-select></el-form-item><el-form-item label="开票备注"><el-input v-model="draft.开票备注" type="textarea" aria-label="开票备注"/></el-form-item></el-form><OrderCostFacts v-else :entries="['收件人','复核人','开票备注'].map(key=>[key,displayValue(face[key])])"/></section></template>
        <section><h2>申请明细</h2><RecordQueryTable :rows="active.lines" :columns="INVOICE_LINES" name="开票申请来源明细" :page-size="5" :exportable="false"><template #cell="{row,field}"><el-input v-if="draft&&field==='本次开票金额(原币)'" v-model="row[field]" :aria-label="`本次开票金额 ${row.id}`"/><template v-else>{{displayValue(row[field])}}</template></template></RecordQueryTable></section>
        <section v-if="selected?.invoiceId||tab==='tax'"><h2>发票信息</h2><OrderCostFacts :entries="TAX_INVOICES.map(([key,label])=>[label,displayValue((tab==='tax'?selected:state.invoicing.taxInvoices.find(row=>row.id===selected.invoiceId))?.[key])])"/><el-button :icon="Download" @click="downloadRecords('合成发票信息.csv',[tab==='tax'?selected:state.invoicing.taxInvoices.find(row=>row.id===selected.invoiceId)],TAX_INVOICES)">下载发票信息 CSV</el-button><el-button v-if="tab==='tax'&&selected.作废==='否'" disabled title="接收人来源、授权及附件契约待确认（215）">发送邮件</el-button></section>
        <div v-if="draft||(selected?.状态==='新建'&&tab!=='backfill')" class="commands"><el-button disabled>保存申请（开票余额待确认）</el-button><el-button disabled>提交开票</el-button></div>
      </template>
    </template>
  </div>
</template>

<style scoped>
.invoice-view{min-width:0}.el-alert{margin:12px 0}section{border-top:1px solid var(--border);padding:20px 0;min-width:0}h2{font-size:15px;margin:0 0 16px}.invoice-form{display:grid;grid-template-columns:repeat(auto-fit,minmax(min(100%,220px),1fr));gap:16px}.invoice-view section>.el-select{max-width:400px;margin:0 12px 16px 0}.commands{display:flex;flex-wrap:wrap;gap:10px;padding:16px 0}.commands .el-button{margin:0}
</style>
