<script setup>
import {computed,ref} from 'vue'
import PageHeader from '../components/PageHeader.vue'
import RecordQueryTable from '../components/RecordQueryTable.vue'
import OperationsChart from '../components/OperationsChart.vue'
import {usePrototypeData} from '../data/usePrototypeData.js'
import {canReadModule} from '../data/accessControl.js'
import {operationsOverview,airlineRanking,SCREEN_SERVICES} from '../domain/operationsScreen.js'
const {state}=usePrototypeData(),period=ref('day'),allowed=computed(()=>canReadModule('bigscreen'))
const label=computed(()=>({day:'本日',month:'本月',year:'本年'})[period.value]),overview=computed(()=>allowed.value?operationsOverview(state,period.value):{}),allAirlines=computed(()=>allowed.value?airlineRanking(state,period.value,'2026-09-08',Infinity):[]),ranking=computed(()=>allAirlines.value.slice(0,10))
const format=value=>value==null?'待确认':Number(value).toLocaleString('zh-CN',{maximumFractionDigits:2})
const comparisons=computed(()=>['订单数','订货量','客户数','航司出货量'].map((metric,index)=>({id:metric,metric,unit:index===1||index===3?'kg':index===0?'单':'个',current:index===0?overview.value.orders:index===1?overview.value.volume:index===2?overview.value.customers:allAirlines.value.some(row=>row.weight==null)?null:allAirlines.value.reduce((sum,row)=>sum+row.weight,0),previous:null,change:null})))
</script>
<template><div class="module-view operations-screen"><PageHeader title="高捷物流运营大屏"><template #actions><el-radio-group v-model="period" aria-label="大屏统计周期"><el-radio-button value="day">本日</el-radio-button><el-radio-button value="month">本月</el-radio-button><el-radio-button value="year">本年</el-radio-button></el-radio-group></template></PageHeader><el-empty v-if="!allowed" description="运营大屏角色尚未确认，仅超级管理员可查看演示数据"/>
  <template v-else><div class="screen-dateline">2026-09-08 · 本地演示数据</div><el-alert title="当前为源记录核对预览。服务统计、历史快照、毛利币种与权限口径待确认（104、220、221）；未生成正式统计快照。" type="warning" :closable="false"/>
    <section class="overview-band" aria-label="业务总览"><div v-for="[key,title,unit] in [['customers','下单客户数','个'],['orders','下单订单数','单'],['volume','下单订货量','kg'],['newCustomers','新增客户','个']]" :key="key"><span>{{label}}{{title}}</span><strong>{{format(overview[key])}}<small v-if="overview[key]!=null">{{unit}}</small></strong></div></section>
    <section class="screen-section"><h2>{{label}}航司出货量</h2><p class="status-copy">按建单期核对；正式航司出货归期及多订舱服务计数待确认（220）。</p><div class="ranking-layout"><OperationsChart v-if="ranking.some(row=>row.weight!=null)" :rows="ranking" :label="`${label}航司出货量，单位kg`"/><el-empty v-else description="没有完整的出货重量"/><RecordQueryTable :rows="ranking" :columns="[['rank','排名',80],['airline','航司',160],['weight','出货量(kg)',160]]" name="航司出货量" :page-size="10" :exportable="false"><template #cell="{row,field}">{{field==='weight'?format(row[field]):row[field]}}</template></RecordQueryTable></div></section>
    <section class="screen-section"><h2>{{label}}服务订单完成状况</h2><RecordQueryTable :rows="SCREEN_SERVICES" :columns="[['name','服务类型',180],['total','服务单总数(单)',200],['completed','已完成服务单数(单)',220]]" name="服务完成状况" :exportable="false"><template #cell="{row,field}">{{row[field]??'统计口径待确认'}}</template></RecordQueryTable></section>
    <section v-if="period!=='day'" class="screen-section"><h2>{{period==='month'?'月度':'年度'}}环比</h2><RecordQueryTable :rows="comparisons" :columns="[['metric','指标',170],['unit','单位',90],['current',period==='month'?'本月':'本年',160],['previous',period==='month'?'上月':'上年',160],['change','环比(%)',200]]" name="环比指标" :exportable="false"><template #cell="{row,field}">{{['current','previous','change'].includes(field)?row[field]==null?field==='previous'?'历史快照未提供':'待确认':format(row[field]):row[field]}}</template></RecordQueryTable></section>
    <section class="screen-section"><h2>毛利金额一览</h2><div class="profit-band"><div><span>当月毛利（万）</span><strong>币种及归期待确认</strong></div><div><span>当年毛利（万）</span><strong>币种及归期待确认</strong></div></div></section>
  </template></div></template>
<style scoped>.operations-screen{min-width:0}.screen-dateline{font-size:13px;color:var(--muted);margin-bottom:16px}.overview-band{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));border-bottom:1px solid var(--border);padding:28px 0;gap:24px}.overview-band>div{border-left:3px solid #258b91;padding-left:16px}.overview-band>div:nth-child(2){border-color:#4b72ba}.overview-band>div:nth-child(3){border-color:#bd8a25}.overview-band>div:nth-child(4){border-color:#8b7498}.overview-band span,.profit-band span{display:block;font-size:13px;color:var(--muted);margin-bottom:12px}.overview-band strong{font-size:28px;font-weight:600;overflow-wrap:anywhere}.overview-band small{font-size:13px;font-weight:400;margin-left:8px}.screen-section{border-bottom:1px solid var(--border);padding:24px 0;min-width:0}.screen-section h2{font-size:16px;margin:0 0 16px}.ranking-layout{display:grid;grid-template-columns:minmax(0,1fr) minmax(0,1fr);gap:24px}.status-copy{font-size:13px;color:var(--muted);line-height:1.6}.profit-band{display:flex;gap:60px;flex-wrap:wrap}.profit-band strong{font-size:18px;color:#63747a;font-weight:500}@media(max-width:1000px){.overview-band{grid-template-columns:repeat(2,minmax(0,1fr))}.ranking-layout{grid-template-columns:1fr}}@media(max-width:540px){.overview-band{gap:24px 12px}.overview-band strong{font-size:23px}.overview-band>div{padding-left:10px}}</style>
