const {chromium,expect}=require(process.env.PLAYWRIGHT_TEST_PATH||'playwright/test')
const {mkdirSync}=require('node:fs')
const {join}=require('node:path')
const output=join(process.cwd(),'test-results','chapters26to33');mkdirSync(output,{recursive:true})
;(async()=>{
  const browser=await chromium.launch({headless:true}),page=await browser.newPage({viewport:{width:1440,height:1000}}),errors=[]
  page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text())})
  async function role(label){await page.getByRole('button',{name:'切换演示角色',exact:true}).click();const input=page.getByRole('combobox',{name:'演示角色',exact:true});await page.locator('.el-select').filter({has:input}).click();const id=await input.getAttribute('aria-controls');await page.locator(`[id="${id}"]`).getByRole('option',{name:label,exact:true}).click();await page.getByRole('button',{name:'切换角色',exact:true}).click()}
  async function route(path){await page.evaluate(path=>{location.hash=path},path)}
  async function shot(name,width=1440){await page.setViewportSize({width,height:1000});await expect.poll(()=>page.locator('.workspace').evaluate(el=>el.getBoundingClientRect().left)).toBe(width>900?224:0);await expect(page.locator('.el-message')).toHaveCount(0);await page.evaluate(()=>window.scrollTo({top:0,behavior:'instant'}));await expect.poll(()=>page.evaluate(()=>window.scrollY)).toBe(0);await expect.poll(()=>page.evaluate(()=>document.documentElement.scrollWidth)).toBeLessThanOrEqual(width);await page.screenshot({path:join(output,name),fullPage:true})}
  try{
    await page.goto('http://localhost:10530/#/workspace');await expect(page.getByRole('heading',{name:'超级管理员工作台',exact:true})).toBeVisible()
    await route('/finance/writeoffs');await expect(page.getByRole('heading',{name:'收付款核销',exact:true})).toBeVisible()
    await expect(page.locator('[aria-label="收款核销列表"] .el-table__row')).toHaveCount(3)
    await page.getByRole('textbox',{name:'查询核销号',exact:true}).fill('no-match');await expect(page.locator('[aria-label="收款核销列表"] .el-table__row')).toHaveCount(3)
    await page.getByRole('button',{name:'查询',exact:true}).click();await expect(page.locator('[aria-label="收款核销列表"] .el-table__row')).toHaveCount(0)
    await page.getByRole('button',{name:'重置',exact:true}).click();await page.getByRole('button',{name:'查看',exact:true}).first().click()
    await expect(page.getByRole('heading',{name:'核销明细',exact:true})).toBeVisible();await shot('26-writeoff-detail.png');await shot('26-writeoff-mobile.png',390)
    await page.getByRole('button',{name:'返回列表',exact:true}).click();await page.setViewportSize({width:1440,height:1000})
    await route('/finance/reimbursements');await expect(page.locator('[aria-label="报销记录"] .el-table__row')).toHaveCount(3)
    await page.locator('[aria-label="报销记录"] .el-table__header-wrapper .el-checkbox').click();await page.getByRole('button',{name:'核销录入',exact:true}).click()
    await expect(page.getByText('借支核销金额等于报销核销金额加退款核销金额',{exact:true})).toBeVisible()
    await page.getByRole('textbox',{name:'本次核销金额 DD-LOAN-002',exact:true}).fill('999');await expect(page.getByText('借支核销金额必须等于报销核销金额加退款核销金额',{exact:true})).toBeVisible()
    await shot('27-offset-preview.png');await shot('27-offset-mobile.png',390)
    await page.getByRole('button',{name:'返回列表',exact:true}).first().click();await page.locator('.el-message-box').getByRole('button',{name:'确认',exact:true}).click()
    await page.setViewportSize({width:1440,height:1000});await page.locator('[aria-label="报销记录"] .el-table__row').filter({hasText:'DD-EXP-003'}).getByRole('button',{name:'查看',exact:true}).click();await expect(page.getByRole('heading',{name:'资产明细',exact:true})).toBeVisible()
    await route('/finance/invoices?tab=backfill');await page.getByRole('button',{name:'查看',exact:true}).click();await expect(page.getByRole('button',{name:'提交补录',exact:true})).toBeDisabled()
    await role('财务会计 · 财务会计演示员');await page.getByRole('button',{name:'查看',exact:true}).click()
    const invoiceInput=page.getByRole('combobox',{name:'补录发票号',exact:true});await page.locator('.el-select').filter({has:invoiceInput}).click();await page.getByRole('option',{name:'DEMO-TAX-260908002',exact:true}).click()
    await page.getByRole('button',{name:'提交补录',exact:true}).click();await page.locator('.el-message-box').getByRole('button',{name:'确认',exact:true}).click();await expect(page.locator('dd').filter({hasText:/^已补录$/})).toBeVisible()
    await shot('28-backfilled-invoice.png');await shot('28-backfilled-mobile.png',390)
    await page.setViewportSize({width:1440,height:1000});await role('超级管理员 · 演示管理员');await route('/finance/statement-templates?statement=BL26090700001')
    await expect(page.getByRole('heading',{name:'客户对账单模板',exact:true})).toBeVisible();await expect(page.locator('.el-table__row')).toHaveCount(1);await shot('29-template-preview.png')
    await route('/foundation/messages');await page.getByRole('tab',{name:'定时提醒预览',exact:true}).click();await expect(page.locator('[aria-label="消息通知"] .el-table__row')).not.toHaveCount(0)
    await page.getByRole('button',{name:'查看',exact:true}).first().click();await expect(page.getByRole('heading',{name:'完整内容',exact:true})).toBeVisible();await shot('30-notification-preview.png')
    await route('/foundation/reports?report=warehouse-customer');await expect(page.getByRole('heading',{name:'仓库客户贡献度月报',exact:true})).toBeVisible();await expect(page.locator('.el-table__row')).not.toHaveCount(0);await shot('31-warehouse-report.png')
    await role('财务主管 · 财务主管演示员');await route('/foundation/reports?report=company-profit');await expect(page.getByRole('button',{name:'提交报表生成申请',exact:true})).toBeDisabled();await shot('31-finance-report-mobile.png',390)
    await route('/foundation/reports?report=warehouse-customer');await expect(page.getByText('当前岗位未获该报表访问授权',{exact:true})).toBeVisible()
    await page.setViewportSize({width:1440,height:1000});await role('超级管理员 · 演示管理员');await route('/foundation/bigscreen');await expect(page.locator('.operations-chart canvas')).toHaveCount(1)
    await expect.poll(()=>page.locator('.operations-chart canvas').evaluate(canvas=>{const data=canvas.getContext('2d').getImageData(0,0,canvas.width,canvas.height).data;let count=0;for(let i=3;i<data.length;i+=4)if(data[i])count++;return count})).toBeGreaterThan(1000)
    await shot('32-operations-desktop.png');await page.getByText('本月',{exact:true}).click();await expect(page.getByRole('heading',{name:'月度环比',exact:true})).toBeVisible();await shot('32-operations-mobile.png',390)
    await page.setViewportSize({width:1440,height:1000});await route('/foundation/ddp-flows');await expect(page.getByRole('heading',{name:'DDP 跨模块作业与结算',exact:true})).toBeVisible()
    await expect(page.locator('[aria-label="DDP关联单据"] .el-table__row')).toHaveCount(3)
    await page.getByRole('textbox',{name:'试算入仓重量',exact:true}).fill('103');await page.getByRole('textbox',{name:'试算报关重量',exact:true}).fill('100')
    await expect(page.getByText('重量误差等于3%，处理边界待确认（222）',{exact:true})).toBeVisible()
    await page.getByRole('textbox',{name:'试算入仓重量',exact:true}).fill('104');await expect(page.getByText('需空运或航晟物流客户部人工确认重量，再由业务系统报送',{exact:true})).toBeVisible()
    await expect(page.getByRole('button',{name:'发送预配',exact:true})).toBeDisabled();await shot('33-ddp-desktop.png');await shot('33-ddp-mobile.png',390)
    await page.locator('[aria-label="DDP关联单据"] .el-table__row').filter({hasText:'仓库作业'}).getByRole('button',{name:'查看',exact:true}).click();await expect(page).toHaveURL(/warehouse-orders.*order=WH-260908-006/)
    await expect(page.getByText('IN-DEMO-019-01',{exact:true}).first()).toBeVisible()
    expect(errors).toEqual([]);console.log('chapters26-33 browser passed: finance previews, invoice backfill, templates, notifications, report roles, operations canvas, DDP boundaries and warehouse deep link')
  }catch(error){console.error('Browser errors:',errors);await page.screenshot({path:join(output,'failure.png'),fullPage:true});throw error}finally{await browser.close()}
})().catch(error=>{console.error(error);process.exitCode=1})
