const { chromium, expect } = require(process.env.PLAYWRIGHT_TEST_PATH || 'playwright/test')
const { mkdirSync, readFileSync } = require('node:fs')
const { join } = require('node:path')
const output = join(process.cwd(), 'test-results', 'chapter25')
mkdirSync(output, { recursive: true })

;(async () => {
  const browser = await chromium.launch({ headless: true })
  const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } })
  const errors = []
  page.on('pageerror', error => errors.push(error.message))
  page.on('console', message => { if (message.type() === 'error') errors.push(message.text()) })
  const rows = () => page.locator('[aria-label="申请列表"] .el-table__row')
  const lines = () => page.locator('[aria-label="申请明细"] .el-table__row')
  const application = id => rows().filter({ hasText: id })
  async function select(name, value) {
    const input = page.getByRole('combobox', { name, exact: true })
    await page.locator('.el-select').filter({ has: input }).click()
    const id = await input.getAttribute('aria-controls')
    await page.locator(`[id="${id}"]`).getByRole('option', { name: value, exact: true }).click()
    await expect(page.locator(`[id="${id}"]`)).toBeHidden()
  }
  async function role(value) {
    await page.getByRole('button', { name: '切换演示角色', exact: true }).click()
    await select('演示角色', value)
    await page.getByRole('button', { name: '切换角色', exact: true }).click()
  }
  async function confirm() { await page.locator('.el-message-box').getByRole('button', { name: '确认', exact: true }).click() }
  async function tab(name) { await page.getByRole('tab', { name, exact: true }).click() }
  async function route(hash) { await page.evaluate(hash => { location.hash = hash }, hash) }
  async function shot(name, width) {
    await page.setViewportSize({ width, height: 1000 })
    await expect.poll(() => page.locator('.workspace').evaluate(el => el.getBoundingClientRect().left)).toBe(width > 900 ? 224 : 0)
    await expect(page.locator('.el-message-box')).toBeHidden()
    await expect(page.locator('.el-message')).toHaveCount(0)
    await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(width)
    await page.screenshot({ path: join(output, name), fullPage: true })
  }
  async function download(button, name) {
    const pending = page.waitForEvent('download'); await button.click()
    const file = await pending; await file.saveAs(join(output, name || file.suggestedFilename()))
    return readFileSync(join(output, name || file.suggestedFilename()))
  }
  try {
    await page.goto((process.env.PROTOTYPE_URL || 'http://localhost:10530') + '/#/finance/payment-requests?kind=payment')
    await expect(page.getByRole('heading', { name: '收付款申请', exact: true })).toBeVisible()
    await expect(rows()).toHaveCount(6)
    await application('RA26090790001').getByRole('button', { name: '查看', exact: true }).click()
    await expect(page.getByRole('heading', { name: '税务发票信息', exact: true })).toBeVisible()
    await expect(page.getByRole('button', { name: '保存并提交', exact: true })).toHaveCount(0)
    await page.getByRole('button', { name: '返回列表', exact: true }).first().click()
    await tab('付款发票补录'); await expect(rows()).toHaveCount(1)
    await page.getByRole('button', { name: '补录详情', exact: true }).click()
    await expect(page.getByRole('button', { name: '提交发票补录', exact: true })).toBeDisabled()
    await shot('01-payment-readonly.png', 1440)
    await role('空运客服 · 周倩')
    await route('/finance/reconciliation?tab=pending&direction=应收')
    const source = page.locator('[aria-label="对账明细"] .el-table__row').filter({ hasText: '1,200.00' })
    await source.locator('.el-checkbox').click()
    await page.getByRole('button', { name: '按勾选创建', exact: true }).click()
    await page.getByRole('button', { name: '保存并确认', exact: true }).click(); await confirm()
    await role('财务会计 · 财务会计演示员')
    await route('/finance/payment-requests?kind=receipt&tab=pending')
    await expect(lines()).toHaveCount(1)
    await lines().locator('.el-checkbox').click()
    await page.getByRole('button', { name: '按勾选创建', exact: true }).click()
    await expect(page.getByRole('heading', { name: '新建收款申请', exact: true })).toBeVisible()
    const amount = page.getByRole('textbox', { name: '本次申请金额 COST-24-DEMO-1', exact: true })
    await amount.fill('0')
    await page.getByRole('button', { name: '保存申请', exact: true }).click()
    await expect(page.getByText('零金额能否保存存在冲突（202），请填写大于0的金额', { exact: true })).toBeVisible()
    await amount.fill('1201'); await expect(page.getByText('本次申请金额不得大于可申请金额', { exact: true })).toBeVisible()
    await amount.fill('600')
    await select('收款账号', '00000010001 演示银行甲 合成公司甲基本户')
    await expect(page.getByRole('button', { name: '保存并提交', exact: true })).toBeDisabled()
    await page.getByRole('button', { name: '保存收款账户', exact: true }).click()
    await expect(page.locator('dd').filter({ hasText: /^演示银行甲$/ })).toBeVisible()
    await page.getByRole('textbox', { name: '申请备注', exact: true }).fill('=合成,"备注"\n第二行')
    const bytes = Buffer.from('chapter25 attachment\nsynthetic proof\n')
    await page.getByLabel('选择申请附件', { exact: true }).setInputFiles({ name: 'receipt-proof.txt', mimeType: 'text/plain', buffer: bytes })
    await expect(page.getByText(/receipt-proof.txt/)).toBeVisible()
    await page.getByLabel('选择申请附件', { exact: true }).setInputFiles({ name: 'rejected.html', mimeType: 'text/html', buffer: Buffer.from('<p>rejected</p>') })
    await expect(page.getByText(/其他文档格式待确认（206）/)).toBeVisible()
    await page.getByRole('button', { name: '返回列表', exact: true }).first().click()
    await page.locator('.el-message-box').getByRole('button', { name: '取消', exact: true }).click()
    await expect(amount).toHaveValue('600')
    await shot('02-receipt-draft-tablet.png', 820)
    await shot('03-receipt-draft-mobile.png', 390)
    await amount.scrollIntoViewIfNeeded()
    await expect(amount).toBeInViewport()
    const amountBox = await amount.boundingBox()
    expect(amountBox.x).toBeGreaterThanOrEqual(0); expect(amountBox.x + amountBox.width).toBeLessThanOrEqual(390)
    await amount.fill('650'); await expect(page.getByLabel('申请合计')).toContainText('650.00')
    await amount.fill('600')
    await page.setViewportSize({ width: 1440, height: 1000 })
    await page.getByRole('button', { name: '保存并提交', exact: true }).click(); await confirm()
    await expect(lines()).toHaveCount(1)
    await expect(lines()).toContainText('600.00')
    await tab('收款申请列表'); await expect(application('RA26090800001')).toContainText('已提交')
    await route('/workspace')
    const task = page.locator('.el-table__row').filter({ hasText: '收款申请审批' })
    await task.getByRole('button', { name: '立即审批', exact: true }).click()
    await expect(page.getByRole('heading', { name: '收款申请审批', exact: true })).toBeVisible()
    await page.getByRole('textbox', { name: '本次审批意见', exact: true }).fill('请核对费用依据')
    await page.getByRole('button', { name: '审批拒绝', exact: true }).click(); await confirm()
    await expect(application('RA26090800001')).toContainText('财务审批拒绝')
    await application('RA26090800001').getByRole('button', { name: '提交', exact: true }).click(); await confirm()
    await application('RA26090800001').getByRole('button', { name: '审批', exact: true }).click()
    await page.getByRole('textbox', { name: '本次审批意见', exact: true }).fill('核对无误')
    await page.getByRole('button', { name: '审批通过', exact: true }).click(); await confirm()
    await expect(application('RA26090800001')).toContainText('财务审批通过')
    await application('RA26090800001').getByRole('button', { name: '查看', exact: true }).click()
    expect(await download(page.getByRole('button', { name: '下载附件', exact: true }), 'receipt-proof.txt')).toEqual(bytes)
    await shot('04-approved-detail.png', 1440)
    await route('/finance/writeoffs?kind=receipt&tab=pending')
    const writeoffRows=page.locator('[aria-label="收款核销来源"] .el-table__row')
    await expect(writeoffRows).toHaveCount(1)
    await expect(writeoffRows).toContainText('RA26090800001')
    await page.getByRole('button',{name:'按查询条件录入',exact:true}).click()
    await expect(page.getByRole('heading',{name:'收款核销录入预览',exact:true})).toBeVisible()
    await page.getByRole('textbox',{name:/本次核销金额 RA26090800001:/}).fill('600')
    await expect(page.getByRole('button',{name:'保存核销',exact:true})).toBeDisabled()
    await page.getByRole('button',{name:'返回列表',exact:true}).first().click();await confirm()
    await route('/finance/payment-requests?kind=receipt&application=RA26090800001')
    await page.getByRole('button', { name: '返回列表', exact: true }).first().click()
    await tab('待收款申请列表')
    await page.getByRole('button', { name: '按查询条件创建', exact: true }).click()
    await expect(amount).toHaveValue('600')
    await page.getByRole('button', { name: '保存申请', exact: true }).click(); await confirm()
    await tab('收款申请列表')
    await application('RA26090800002').getByRole('button', { name: '删除', exact: true }).click(); await confirm()
    await expect(rows()).toHaveCount(1)
    await rows().locator('.el-checkbox').click()
    const csv = (await download(page.getByRole('button', { name: '按查询条件批量导出', exact: true }), 'receipts.csv')).toString('utf8')
    expect(csv.charCodeAt(0)).toBe(0xFEFF); expect(csv).toContain('"RA26090800001"'); expect(csv).not.toContain('RA26090800002')
    expect(csv).toContain('"\'=合成,""备注""\n第二行"'); expect(csv).toContain('"33.96"')
    await page.getByRole('textbox', { name: '查询申请批次号', exact: true }).fill('no-match')
    await expect(rows()).toHaveCount(1)
    await page.getByRole('button', { name: '查询', exact: true }).click(); await expect(rows()).toHaveCount(0)
    await page.getByRole('button', { name: '重置', exact: true }).click(); await expect(rows()).toHaveCount(1)
    await route('/foundation/messages')
    await expect(page.locator('.el-table__row').filter({ hasText: 'RA26090800001' })).toHaveCount(4)
    await role('超级管理员 · 演示管理员')
    await route('/finance/payment-requests?kind=receipt&application=RA26090800001&view=approve')
    await expect(page.getByRole('button', { name: '审批通过', exact: true })).toBeDisabled()
    await shot('05-admin-mobile.png', 390)
    expect(errors).toEqual([])
    console.log('GJ-025 browser passed: confirmed reconciliation -> partial receipt -> account/file save -> submit -> workbench rejection/resubmit/approval -> remaining amount/delete/export/messages; payment read-only; desktop/tablet/mobile.')
  } catch (error) {
    await page.screenshot({ path: join(output, 'failure.png'), fullPage: true })
    throw error
  } finally { await browser.close() }
})().catch(error => { console.error(error); process.exitCode = 1 })
