import { beforeEach, describe, expect, it } from 'vitest'
import { readFileSync } from 'node:fs'
import { parse, compileScript, compileTemplate } from '@vue/compiler-sfc'
import { usePrototypeData } from '../src/data/usePrototypeData.js'
import { groundServiceDraft, groundRecord, groundPackageDone, groundArrivalSummary, groundServiceErrors, groundAccount } from '../src/domain/groundService.js'
import { canReadModule, groundServicePermissions, saveGroundServicePermissions, rolePermissionDraft, saveRolePermissions } from '../src/data/accessControl.js'
const data = usePrototypeData()
const image = { name: 'proof.png', type: 'image/png', size: 8, dataUrl: 'data:image/png;base64,iVBORw0KGgo=' }
const draft = (number, extra = {}) => ({ ...groundServiceDraft(), number, ...extra })
async function login(persona) { data.selectWorkbenchPersona(persona); await data.loginDriver({ phone: groundAccount(persona).phone, method: 'wechat', remember: false }) }
beforeEach(() => { data.reset(); data.selectWorkbenchPersona('superAdmin'); data.loadDemoOverview() })
describe('第019篇单据与共享会话', () => {
  it('单证必传、单号重新匹配、创建和改单保留账户操作记录', async () => {
    await login('groundWarehouse')
    expect(() => data.submitGroundService('document', draft('UNKNOWN', { images: [image] }))).toThrow('无法匹配')
    expect(() => data.submitGroundService('document', draft('IN-DEMO-019-01'))).toThrow('至少上传')
    const row = data.submitGroundService('document', draft('IN-DEMO-019-01', { images: [image] }))
    expect(row.warehouseId).toBe('WH-260908-006'); expect(row.history[0].actorId).toBe('DEMO-GROUND-WH')
    data.submitGroundService('document', draft('IN-DEMO-019-02', { images: [image], remark: '改单确认' }), row.id, row.revision)
    expect(groundRecord(data.state, 'document', 'IN-DEMO-019-01')).toBeUndefined()
    expect(groundRecord(data.state, 'document', 'IN-DEMO-019-02').id).toBe(row.id)
    expect(row.history.map(item => item.action)).toEqual(['提交', '修改'])
    expect(row.history[1].previousNumber).toBe('IN-DEMO-019-01')
  })
  it('跨记录覆盖及旧版本修改拒绝，失败不影响已有数据', async () => {
    await login('groundWarehouse')
    const a = data.submitGroundService('document', draft('IN-DEMO-019-01', { images: [image] }))
    data.submitGroundService('document', draft('IN-DEMO-019-02', { images: [image] }))
    const before = JSON.stringify(data.state.groundServiceRecords)
    expect(() => data.submitGroundService('document', draft('IN-DEMO-019-02', { images: [image] }), a.id, 1)).toThrow('不能覆盖')
    expect(() => data.submitGroundService('document', draft('IN-DEMO-019-01', { images: [image] }), a.id, 0)).toThrow('记录已变化')
    expect(JSON.stringify(data.state.groundServiceRecords)).toBe(before)
  })
  it('出库托盘独立匹配，图片及备注边界', async () => {
    await login('groundWarehouse')
    expect(() => data.submitGroundService('outbound', draft('IN-DEMO-019-01', { images: [image] }))).toThrow('无法匹配')
    expect(() => data.submitGroundService('outbound', draft('PALLET-DEMO-019-01', { images: Array(16).fill(image) }))).toThrow('15')
    expect(() => data.submitGroundService('outbound', draft('PALLET-DEMO-019-01', { images: [image], remark: '一' }))).toThrow('2～500')
    expect(data.submitGroundService('outbound', draft('PALLET-DEMO-019-01', { images: [image] })).target).toBe('仓库')
  })
  it('非授权身份、跨岗位操作及管理员写入均拒绝', async () => {
    expect(() => data.submitGroundService('document', draft('IN-DEMO-019-01', { images: [image] }))).toThrow('授权')
    await login('groundStation')
    expect(() => data.submitGroundService('document', draft('IN-DEMO-019-01', { images: [image] }))).toThrow('授权')
    data.selectWorkbenchPersona('service')
    expect(() => data.getGroundServiceRecords('document')).toThrow('授权')
    expect(data.driverSession.phone).toBe('')
  })
  it('司机第三页签使用同一不记住登录会话，不能访问后台运单', async () => {
    await login('driver'); await data.enterDriver()
    expect(data.driverSession.phone).toBe('00000001801')
    expect(canReadModule('groundService')).toBe(true); expect(canReadModule('groundWaybills')).toBe(false)
    expect(data.submitGroundService('driverHandin', draft('781-90000001')).operation).toBe('driverHandin')
    expect(() => data.submitGroundService('driverHandin', draft('781-90000002'))).toThrow('159')
    await data.logoutDriver(); expect(() => data.submitGroundService('driverHandin', draft('781-90000001'))).toThrow('登录')
  })
  it('管理员可收紧逐操作权限，不可扩张岗位；已打开页面也不能绕过撤权', async () => {
    await login('groundWarehouse')
    data.selectWorkbenchPersona('superAdmin')
    expect(() => saveGroundServicePermissions('groundWarehouse', ['driverHandin'])).toThrow('扩张')
    saveGroundServicePermissions('groundWarehouse', ['returnIn'])
    await login('groundWarehouse')
    expect(groundServicePermissions('groundWarehouse')).toEqual(['returnIn'])
    expect(() => data.submitGroundService('document', draft('IN-DEMO-019-01', { images: [image] }))).toThrow('授权')
    data.selectWorkbenchPersona('superAdmin')
    const policy = rolePermissionDraft('groundWarehouse'); policy.groundService.write = false; saveRolePermissions('groundWarehouse', policy)
    await login('groundWarehouse')
    expect(() => data.submitGroundService('returnIn', draft('781-90000001', { packages: ['PKG-019-A'] }))).toThrow('授权')
  })
})
describe('第019篇批量逆向链路与空运结果', () => {
  it('电商退货→退件入库→退件出库共用包裹状态，去重且保留提货人', async () => {
    await login('groundWarehouse')
    expect(() => data.submitGroundService('returnIn', draft('781-90000001', { packages: ['PKG-019-A'] }))).toThrow('部分包裹码无效')
    await login('groundStation')
    const returned = data.submitGroundService('return', draft('781-90000001', { packages: ['PKG-019-A', 'PKG-019-A', 'PKG-019-B'] }))
    expect(returned.packages).toEqual(['PKG-019-A', 'PKG-019-B'])
    await login('groundWarehouse')
    data.submitGroundService('returnIn', draft('781-90000001', { packages: ['PKG-019-A', 'PKG-019-B'] }))
    const row = data.submitGroundService('returnOut', draft('781-90000001', { packages: ['PKG-019-A'], collectorName: '提货演示员', collectorPhone: '10000000', collectorPlate: '沪A-DEMO' }))
    expect(row.collectorName).toBe('提货演示员'); expect(groundPackageDone(data.state, 'returnOut', row.number, 'PKG-019-A')).toBe(true)
    expect(() => data.submitGroundService('returnOut', row, row.id, row.revision)).toThrow('不支持修改')
  })
  it('混合无效包裹整批不写，重复已提交包裹可成功，空行需修正', async () => {
    await login('groundStation')
    const before = JSON.stringify(data.state.groundServiceRecords)
    const bad = draft('781-90000001', { packages: ['PKG-019-A', 'WRONG'] })
    expect(groundServiceErrors(data.state, 'return', bad).invalidRows).toEqual([1])
    expect(() => data.submitGroundService('return', bad)).toThrow('部分包裹码无效')
    expect(JSON.stringify(data.state.groundServiceRecords)).toBe(before)
    data.submitGroundService('return', draft('781-90000001', { packages: ['PKG-019-A'] }))
    expect(() => data.submitGroundService('return', draft('781-90000001', { packages: ['PKG-019-A', 'PKG-019-B'] }))).not.toThrow()
    expect(groundServiceErrors(data.state, 'return', draft('781-90000001', { packages: ['PKG-019-A', ''] })).invalidRows).toBeUndefined()
    expect(groundServiceErrors(data.state, 'return', draft('78190000001')).number).toContain('123-12345678')
  })
  it('退件出库选填字段不填合法，填入时执行全部边界', () => {
    const errors = groundServiceErrors(data.state, 'returnOut', draft('781-90000001', { collectorName: '一', collectorPhone: '-1234567', collectorPlate: 'A' }))
    expect(errors.collectorName).toBeTruthy(); expect(errors.collectorPhone).toBeTruthy(); expect(errors.collectorPlate).toBeTruthy()
  })
  it('内部封条须已出库且全部到达才通知，修改不重复通知且阻止不明撤回', async () => {
    await login('groundStation')
    const count = data.state.messages.length
    expect(() => data.submitGroundService('arrival', draft('SEAL-DEMO-019-C'))).toThrow('尚未完成WMS出库')
    const a = data.submitGroundService('arrival', draft('SEAL-DEMO-019-A'))
    expect(data.state.messages).toHaveLength(count)
    data.submitGroundService('arrival', draft('SEAL-DEMO-019-B'))
    expect(groundArrivalSummary(data.state, 'AIR-260908-001')).toEqual({ total: 2, arrived: 2 })
    expect(data.state.messages).toHaveLength(count + 1)
    data.submitGroundService('arrival', draft(a.number, { remark: '补充说明' }), a.id, a.revision)
    expect(data.state.messages).toHaveLength(count + 1)
    expect(() => data.submitGroundService('arrival', draft('EXTERNAL-DEMO-019'), a.id, a.revision)).toThrow('161')
  })
  it('托书图片与普货主订单匹配，回传保持本地模拟', async () => {
    await login('groundStation')
    expect(() => data.submitGroundService('bookingDocument', draft('781-90000001'))).toThrow('至少上传')
    expect(data.submitGroundService('bookingDocument', draft('781-90000001', { images: [image] })).transmission).toBe('本地模拟，未发送')
    const row = data.submitGroundService('generalReturn', draft(data.state.airOrders[0].orderNo))
    expect(row.orderId).toBe(data.state.airOrders[0].id)
    expect(data.state.airOrders[0].orderStatus).toBe('待补录')
  })
})
for (const file of ['views/GroundServiceView.vue', 'components/GroundServiceScanner.vue', 'components/MiniProgramLogin.vue', 'views/DriverTasksView.vue']) it(`${file} SFC可编译`, () => {
  const parsed = parse(readFileSync(new URL(`../src/${file}`, import.meta.url), 'utf8'), { filename: file }); expect(parsed.errors).toEqual([])
  const script = compileScript(parsed.descriptor, { id: file })
  expect(compileTemplate({ source: parsed.descriptor.template.content, filename: file, id: file, compilerOptions: { bindingMetadata: script.bindings } }).errors).toEqual([])
})
