const { chromium, expect } = require(process.env.PLAYWRIGHT_TEST_PATH || 'playwright/test')
const { mkdirSync, readFileSync } = require('node:fs')
const { join } = require('node:path')
const output = join(process.cwd(), 'test-results', 'chapter23')
mkdirSync(output, { recursive: true })

;(async () => {
  const browser = await chromium.launch({ headless: true })
  const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } })
  const errors = []
  page.on('pageerror', error => errors.push(error.message))
  page.on('console', message => { if (message.type() === 'error') errors.push(message.text()) })
  async function select(name, value, root = page) {
    const input = root.getByRole('combobox', { name, exact: true })
    await root.locator('.el-select').filter({ has: page.getByRole('combobox', { name, exact: true }) }).click()
    const id = await input.getAttribute('aria-controls')
    await page.locator(`[id="${id}"]`).getByRole('option', { name: value, exact: true }).click()
    await expect(page.locator(`[id="${id}"]`)).toBeHidden()
  }
  async function role(value) {
    await page.getByRole('button', { name: '切换演示角色', exact: true }).click()
    await select('演示角色', value)
    await page.getByRole('button', { name: '切换角色', exact: true }).click()
  }
  async function confirm() { await page.getByRole('button', { name: '确认', exact: true }).click() }
  const rowWith = text => page.locator('.el-table__row').filter({ hasText: text })
  try {
    await page.goto((process.env.PROTOTYPE_URL || 'http://localhost:10530') + '/#/finance/costs')
    await expect(page.getByRole('heading', { name: '订单成本管理', exact: true })).toBeVisible()
    await expect(page.locator('[aria-label="订单成本列表"] .el-table__row')).toHaveCount(3)
    await expect.poll(()=>page.locator('.workspace').evaluate(el=>el.getBoundingClientRect().left)).toBe(224)
    await page.screenshot({ path: join(output, '01-admin-orders.png') })
    await role('空运客服 · 周倩')
    await rowWith('FINDEMO260901').getByRole('button', { name: '成本编辑', exact: true }).click()
    await page.getByRole('button', { name: '新增应收', exact: true }).click()
    const draft = page.locator('.draft-line')
    await select('(子)单号', 'FINDEMO260901', draft)
    await select('结算单位', '启航跨境贸易', draft)
    await select('成本项目', 'F017 装卸成本', draft)
    for (const [name, value] of [['数量','3'],['计费单位','票'],['税率(%)','6'],['含税单价(原币)','100'],['约定汇率','1.05'],['成本备注','UI-FLOW-23 =演示,"换行"\n附件校验']]) await draft.getByRole('textbox', { name, exact: true }).fill(value)
    await draft.locator('input[type=file]').setInputFiles({ name: 'cost-evidence.txt', mimeType: 'text/plain', buffer: Buffer.from('chapter23 synthetic attachment\n') })
    await expect(draft.getByText(/cost-evidence.txt/)).toBeVisible()
    await page.setViewportSize({ width: 820, height: 1000 })
    await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(820)
    await draft.screenshot({ path: join(output, '02-entry-constrained.png') })
    await page.setViewportSize({ width: 1440, height: 1000 })
    await page.getByRole('button', { name: '保存该行', exact: true }).click()
    await expect(rowWith('UI-FLOW-23')).toContainText('新建')
    await rowWith('UI-FLOW-23').locator('.el-checkbox').click()
    await page.getByRole('button', { name: '提交审批', exact: true }).click()
    await expect(page.locator('.el-message-box')).toContainText('约定汇率高于即期汇率 5.00%')
    await confirm()
    await expect(rowWith('UI-FLOW-23')).toContainText('已提交')
    await page.getByRole('button', { name: '返回列表', exact: true }).click()
    await role('空运客服主管 · 周倩')
    await page.getByRole('tab', { name: '成本审批', exact: true }).click()
    await rowWith('FINDEMO260901').getByRole('button', { name: '审批', exact: true }).click()
    await rowWith('UI-FLOW-23').locator('.el-checkbox').click()
    await page.getByRole('textbox', { name: '整单审批备注', exact: true }).fill('业务核对通过')
    await page.getByRole('button', { name: '审批通过', exact: true }).click(); await confirm()
    await expect(rowWith('UI-FLOW-23')).toHaveCount(0)
    await role('财务会计 · 财务会计演示员')
    await rowWith('UI-FLOW-23').locator('.el-checkbox').click()
    await page.getByRole('button', { name: '审批通过', exact: true }).click(); await confirm()
    await expect(rowWith('UI-FLOW-23')).toHaveCount(0)
    await expect(page.getByText('本地待同步', { exact: true })).toBeVisible()
    await page.screenshot({ path: join(output, '03-finance-approved.png'), fullPage: true })
    await page.getByRole('button', { name: '返回列表', exact: true }).click()
    await role('空运客服 · 周倩')
    await page.getByRole('tab', { name: '调整单', exact: true }).click()
    await page.getByRole('button', { name: '新增调整单', exact: true }).click()
    await rowWith('UI-FLOW-23').locator('.el-checkbox').click()
    await page.getByRole('button', { name: '录入调整单', exact: true }).click()
    const dialog = page.getByRole('dialog', { name: '新增调整单', exact: true })
    await expect(dialog.getByText('新建', { exact: true })).toBeVisible()
    await select('调账责任人', '周倩', dialog)
    await select('调账种类', '3. 错误录入-少录', dialog)
    await dialog.getByRole('textbox', { name: '含税单价(原币)', exact: true }).fill('110')
    await dialog.getByRole('textbox', { name: '调账原因', exact: true }).fill('合成差异核对')
    await dialog.screenshot({ path: join(output, '04-adjustment.png') })
    await dialog.getByRole('button', { name: '保存并提交', exact: true }).click(); await confirm()
    await expect(rowWith('ADJ26090800001')).toContainText('已提交')
    await role('空运客服主管 · 周倩')
    await page.getByRole('tab', { name: '成本审批', exact: true }).click()
    await expect(page.locator('[aria-label="订单成本列表"] .el-table__row').first()).toContainText('ADJ26090800001')
    await rowWith('ADJ26090800001').getByRole('button', { name: '审批', exact: true }).click()
    await page.locator('.cost-line-table').first().locator('.el-table__row .el-checkbox').click()
    await page.getByRole('button', { name: '审批通过', exact: true }).click(); await confirm()
    await role('财务会计 · 财务会计演示员')
    await page.locator('.cost-line-table').first().locator('.el-table__row .el-checkbox').click()
    await expect(page.getByRole('button', { name: '审批通过', exact: true })).toBeDisabled()
    await page.getByRole('button', { name: '审批拒绝', exact: true }).click(); await confirm()
    await expect(page.locator('.cost-line-table').first().locator('.el-table__row')).toHaveCount(0)
    await page.getByRole('button', { name: '返回列表', exact: true }).click()
    await page.getByRole('tab', { name: '明细查询', exact: true }).click()
    await page.getByRole('textbox', { name: '查询订单号', exact: true }).fill('FINDEMO260901')
    await expect(page.locator('.cost-line-table .el-table__row')).toHaveCount(13)
    await page.getByRole('button', { name: '查询', exact: true }).click()
    await expect(page.locator('.cost-line-table .el-table__row')).toHaveCount(5)
    await rowWith('UI-FLOW-23').locator('.el-checkbox').click()
    const downloadPromise = page.waitForEvent('download')
    await page.getByRole('button', { name: '导出勾选', exact: true }).click()
    const download = await downloadPromise, filePath = join(output, download.suggestedFilename())
    await download.saveAs(filePath)
    const csv = readFileSync(filePath, 'utf8')
    expect(csv.startsWith('\uFEFF')).toBe(true)
    expect(csv).toContain('UI-FLOW-23 =演示,""换行""\n附件校验')
    expect(csv).toContain('财务审批通过')
    const queryDownloadPromise=page.waitForEvent('download')
    await page.getByRole('button',{name:'导出查询结果',exact:true}).click()
    const queryDownload=await queryDownloadPromise
    await queryDownload.saveAs(join(output,queryDownload.suggestedFilename()))
    await rowWith('UI-FLOW-23').getByRole('button', { name: '查看', exact: true }).click()
    const detail = page.getByRole('dialog', { name: '结算明细', exact: true })
    const attachmentPromise = page.waitForEvent('download')
    await detail.getByRole('button', { name: '下载附件', exact: true }).click()
    const attachment = await attachmentPromise, attachmentPath = join(output, attachment.suggestedFilename())
    await attachment.saveAs(attachmentPath)
    expect(readFileSync(attachmentPath, 'utf8')).toBe('chapter23 synthetic attachment\n')
    await page.keyboard.press('Escape')
    await expect(detail).toBeHidden()
    await role('超级管理员 · 演示管理员')
    await page.getByRole('tab', { name: '订单成本', exact: true }).click()
    await rowWith('FINDEMO260901').getByRole('button', { name: '查看', exact: true }).click()
    await expect(page.getByRole('button', { name: '新增应收', exact: true })).toHaveCount(0)
    await expect(page.getByRole('button', { name: '提交审批', exact: true })).toHaveCount(0)
    await page.setViewportSize({ width: 390, height: 844 })
    await expect.poll(()=>page.locator('.workspace').evaluate(el=>el.getBoundingClientRect().left)).toBe(0)
    await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(390)
    await page.screenshot({ path: join(output, '05-readonly-mobile.png'), fullPage: true })
    await page.setViewportSize({width:1440,height:1000})
    await role('空运客服 · 周倩')
    const payable=rowWith('业务审批拒绝')
    await payable.getByRole('button',{name:'编辑',exact:true}).click()
    const payableDialog=page.getByRole('dialog',{name:'编辑订单成本',exact:true})
    await payableDialog.getByRole('textbox',{name:'数量',exact:true}).fill('2')
    await payableDialog.getByRole('textbox',{name:'成本备注',exact:true}).fill('UI-AP-23')
    await payableDialog.getByRole('button',{name:'保存',exact:true}).click()
    await expect(rowWith('UI-AP-23')).toContainText('320.00')
    await rowWith('UI-AP-23').locator('.el-checkbox').click()
    await page.getByRole('button',{name:'提交审批',exact:true}).click();await confirm()
    await expect(rowWith('UI-AP-23')).toContainText('已提交')
    await page.getByRole('button',{name:'新增应付',exact:true}).click()
    await expect(page.getByText('结算单位类型待确认（186），新增应付暂不保存。',{exact:true})).toBeVisible()
    await page.getByRole('button',{name:/删除新增行/}).click();await confirm()
    await page.goto((process.env.PROTOTYPE_URL || 'http://localhost:10530')+'/#/foundation/messages')
    await rowWith('财务审批拒绝 · ADJ26090800001').getByRole('button',{name:'查看单据',exact:true}).click()
    await expect(page.getByRole('dialog',{name:'结算明细',exact:true})).toContainText('ADJ26090800001')
    await expect(page.getByRole('dialog',{name:'结算明细',exact:true})).toContainText('财务审批拒绝')
    await page.keyboard.press('Escape')
    expect(errors).toEqual([])
    console.log('PASS: admin read-only, complete fields, attachment bytes, constrained layout, save/submit, FX warning, two approvals, adjustment source/priority/business approval/final gate/rejection, staged query, selected/query CSV download, payable edit/resubmit and new-party gate')
  } catch(error) { await page.screenshot({path:join(output,'failure.png'),fullPage:true});console.error('Browser errors:',errors);console.error(await page.evaluate(()=>[...document.querySelectorAll('body *')].filter(el=>el.getBoundingClientRect().right>innerWidth+5&&getComputedStyle(el).position==='fixed').map(el=>({tag:el.tagName,class:el.className,width:el.getBoundingClientRect().width,right:el.getBoundingClientRect().right})).slice(0,12)));throw error }
  finally { await browser.close() }
})().catch(error => { console.error(error); process.exitCode = 1 })
