import { beforeEach, describe, expect, it } from 'vitest'
import { usePrototypeData } from '../src/data/usePrototypeData.js'
import { costDraft, costAmounts, costTotals, costReference, costOrders, costRows, costErrors, costCsv, matchesCostQuery, fxWarnings, costFileError } from '../src/domain/orderCosts.js'
import { captureOrderCostContext } from '../src/data/orderCostActions.js'
import { canReadModule, canWriteModule, rolePermissionDraft, saveRolePermissions } from '../src/data/accessControl.js'
import { deriveWorkbenchTasks } from '../src/domain/workbenchTasks.js'
const data = usePrototypeData()
const orderId = 'FIN-ORDER-DEMO-001'
function draft(extra={}) { return {...costDraft(data.state),childNo:'FINDEMO260901',partyId:'PT-00018',feeItemId:'COST-003',quantity:'10',unit:'票',taxRate:'6',unitPrice:'100',...extra} }
beforeEach(()=>{data.reset();data.loadOrderCostExamples()})

describe('GJ-023 order costs',()=>{
  it('keeps legacy and unfinished orders out of settlement writes and seeds idempotently',()=>{
    expect(costOrders(data.state)).toHaveLength(2)
    expect(costRows(data.state)).toHaveLength(6)
    data.loadOrderCostExamples();expect(costRows(data.state)).toHaveLength(6)
    expect(data.state.airOrders[0].orderStatus).toBe('待补录')
    expect(()=>data.saveOrderCost(data.state.airOrders[0].id,'',draft())).toThrow('尚未完成')
    expect(()=>data.reviewCost('COST-260908-102',true)).toThrow('授权')
  })
  it('saves a draft separately from submission and recomputes every amount',()=>{
    const row=data.saveOrderCost(orderId,'',draft({amount:90000,spotRate:800,status:'财务审批通过'}))
    expect(row).toMatchObject({status:'新建',amount:1000,originalAmount:1000,spotRate:'1',direction:'应收',createdBy:'周倩'})
    data.saveOrderCost(orderId,row.id,draft({unitPrice:'120'}));expect(row.amount).toBe(1200)
    expect(costTotals(costRows(data.state).filter(item=>item.orderId===orderId)).receivable).toBe(3600)
    data.submitOrderCosts([row.id]);expect(row.status).toBe('已提交')
    expect(()=>data.saveOrderCost(orderId,row.id,draft())).toThrow('当前状态')
    expect(()=>data.deleteOrderCost(row.id)).toThrow('当前状态')
    expect(()=>data.submitOrderCosts([row.id])).toThrow('当前状态')
  })
  it('enforces both approval stages and creates one simulated sync with business posting date',()=>{
    const row=data.saveOrderCost(orderId,'',draft());data.submitOrderCosts([row.id])
    data.selectWorkbenchPersona('financeAccountant');expect(()=>data.reviewOrderCosts([row.id],true)).toThrow('环节')
    data.selectWorkbenchPersona('supervisor');data.reviewOrderCosts([row.id],true,{rowRemarks:{[row.id]:'数量正确'},orderRemark:'核对完成'})
    expect(deriveWorkbenchTasks(data.state,'financeAccountant').some(task=>task.orderId===orderId&&task.type==='cost-approval')).toBe(true)
    const businessDate=row.businessApprovedAt.slice(0,10);expect(row.status).toBe('业务审批通过')
    data.selectWorkbenchPersona('financeAccountant');data.reviewOrderCosts([row.id],true)
    expect(row.status).toBe('财务审批通过');expect(row.approvalRemark).toBe('')
    expect(data.state.orderCostBook.syncEvents).toHaveLength(1)
    expect(data.state.orderCostBook.syncEvents[0]).toMatchObject({costId:row.id,postingDate:businessDate,status:'本地待同步',externalId:''})
    expect(()=>data.reviewOrderCosts([row.id],true)).toThrow('环节');expect(data.state.orderCostBook.syncEvents).toHaveLength(1)
  })
  it('restarts business approval after either rejection, preserving audit history',()=>{
    const row=data.saveOrderCost(orderId,'',draft());data.submitOrderCosts([row.id])
    data.selectWorkbenchPersona('supervisor');data.reviewOrderCosts([row.id],false,{rowRemarks:{[row.id]:'核对税率'}})
    expect(row.status).toBe('业务审批拒绝');expect(row.approvalRemark).toBe('核对税率')
    data.selectWorkbenchPersona('service');data.saveOrderCost(orderId,row.id,draft({taxRate:'0'}));data.submitOrderCosts([row.id])
    data.selectWorkbenchPersona('supervisor');data.reviewOrderCosts([row.id],true)
    data.selectWorkbenchPersona('financeAccountant');data.reviewOrderCosts([row.id],false)
    data.selectWorkbenchPersona('service');data.submitOrderCosts([row.id]);expect(row.status).toBe('已提交');expect(row.businessApprovedAt).toBe('')
    expect(row.history.some(event=>event.remark==='核对税率')).toBe(true)
  })
  it('validates all selected rows before mutating a batch',()=>{
    const rows=costRows(data.state),before=JSON.stringify(data.state.costs)
    expect(()=>data.submitOrderCosts([rows[0].id,rows[1].id])).toThrow('当前状态')
    expect(JSON.stringify(data.state.costs)).toBe(before)
    data.selectWorkbenchPersona('supervisor');expect(()=>data.reviewOrderCosts([rows[1].id,rows[2].id],true)).toThrow('环节')
    expect(JSON.stringify(data.state.costs)).toBe(before)
    expect(()=>data.reviewOrderCosts([rows[1].id,rows[1].id],true)).toThrow('不重复')
  })
  it('calculates FX and reference price, binds rates, and refuses missing mappings',()=>{
    const row=data.saveOrderCost(orderId,'',draft({currency:'USD',agreedRate:'7.5'}))
    expect(row.spotRate).toBe('7.0500');expect(row.amount).toBe(7500);expect(row.premium).toBeGreaterThan(3)
    expect(fxWarnings([row])[0]).toContain('约定汇率高于即期汇率')
    expect(costReference(data.state,orderId,'COST-003')).toBe(140)
    data.selectWorkbenchPersona('financeAccountant');expect(()=>data.editFinanceRate('FX-DEMO-001',{...data.state.financeBasics.rates[0],rate:'7.3'})).toThrow('177')
    data.selectWorkbenchPersona('service')
    expect(()=>data.saveOrderCost(orderId,'',draft({currency:'EUR',agreedRate:'8'}))).toThrow('即期汇率')
    expect(()=>data.saveOrderCost(orderId,'',draft({childNo:'OTHER'}))).toThrow('关联的单号')
    expect(()=>data.saveOrderCost(orderId,'',draft({feeItemId:'FC-0001'}))).toThrow('业务类型')
    expect(()=>data.saveOrderCost(orderId,'',draft({partyId:'PT-00020'}))).toThrow('主体')
  })
  it('limits entry, editing, approvals and permission ceilings without merging financial role names',()=>{
    const row=data.state.costs.find(row=>row.id==='COST-23-DEMO-1')
    data.selectWorkbenchPersona('business');expect(data.saveOrderCost(orderId,'',draft()).status).toBe('新建')
    expect(()=>data.saveOrderCost(orderId,row.id,draft())).toThrow('授权')
    data.selectWorkbenchPersona('finance');expect(canReadModule('costs')).toBe(false);expect(()=>data.reviewOrderCosts([row.id],true)).toThrow('授权')
    data.selectWorkbenchPersona('superAdmin');expect(canReadModule('costs')).toBe(true);expect(canWriteModule('costs')).toBe(false)
    expect(()=>data.saveOrderCost(orderId,'',draft())).toThrow('授权')
    const permission=rolePermissionDraft('service');permission.costs.write=false;data.selectWorkbenchPersona('superAdmin');saveRolePermissions('service',permission)
    data.selectWorkbenchPersona('service');expect(()=>data.saveOrderCost(orderId,'',draft())).toThrow('授权')
  })
  it('retains immutable source snapshots and blocks ambiguous adjustment finalization only',()=>{
    const source=data.state.costs.find(row=>row.id==='COST-23-DEMO-5'),before=JSON.stringify(source)
    const row=data.saveCostAdjustment(source.id,'',{...draft(),childNo:source.childNo,responsibleId:'service',adjustmentType:'3',unitPrice:'150'},true)
    expect(row.adjustmentNo).toBe('ADJ26090800001');expect(row.childNo).toBe(row.adjustmentNo);expect(row.status).toBe('已提交')
    expect(row.sourceSnapshot.id).toBe(source.id);expect(JSON.stringify(source)).toBe(before)
    data.selectWorkbenchPersona('supervisor');data.reviewOrderCosts([row.id],true,{adjustment:true})
    data.selectWorkbenchPersona('financeAccountant');expect(()=>data.reviewOrderCosts([row.id],true,{adjustment:true})).toThrow('188')
    expect(row.status).toBe('业务审批通过');data.reviewOrderCosts([row.id],false,{adjustment:true});expect(row.status).toBe('财务审批拒绝')
    expect(JSON.stringify(source)).toBe(before);expect(data.state.orderCostBook.syncEvents).toHaveLength(0)
  })
  it('validates adjustment ownership, attachment conditions and source eligibility',()=>{
    const source=data.state.costs.find(row=>row.id==='COST-23-DEMO-5')
    expect(()=>data.saveCostAdjustment('COST-23-DEMO-1','',draft())).toThrow('财务审批通过')
    expect(()=>data.saveCostAdjustment(source.id,'',draft({responsibleId:'OTHER-DEMO'}))).toThrow('主体')
    expect(()=>data.saveCostAdjustment(source.id,'',draft({responsibleId:'service',adjustmentType:'9'}))).toThrow('必须提供附件')
    const file={name:'合成.txt',type:'text/plain',size:3,dataUrl:'data:text/plain;base64,YWJj'}
    const row=data.saveCostAdjustment(source.id,'',draft({responsibleId:'service',adjustmentType:'9',attachments:[file]}))
    expect(row.status).toBe('新建');expect(row.attachments).toHaveLength(1)
    expect(()=>data.saveCostAdjustment(source.id,row.id,{...row,attachments:[]})).toThrow('只读')
    data.deleteCostAdjustment(row.id);expect(row.deleted).toBe(true)
  })
  it('handles empty values, ranges, export escaping and stale async contexts',()=>{
    expect(costAmounts({quantity:'',unitPrice:1,agreedRate:1,spotRate:1}).amount).toBe(null)
    expect(costFileError({size:21*1024*1024,type:'text/plain'})).toContain('20MB')
    expect(costFileError({size:3,type:'text/html'})).toContain('格式')
    expect(matchesCostQuery({businessDate:'2026-09-08',status:'新建'},{businessDate:['2026-09-08','2026-09-08'],status:'新建'})).toBe(true)
    expect(matchesCostQuery({createdAt:''},{createdAt:['2026-09-01','2026-09-30']})).toBe(false)
    expect(costCsv([{remark:'=danger,"quoted"\nnext',amount:0}])).toContain('"\'=danger,""quoted""\nnext"')
    expect(costErrors(data.state,costOrders(data.state)[0],draft({taxRate:''})).taxRate).toBeTruthy()
    const current=captureOrderCostContext(data.state);data.selectWorkbenchPersona('supervisor');expect(current()).toBe(false)
    const reset=captureOrderCostContext(data.state);data.reset();expect(reset()).toBe(false)
  })
  it('blocks ambiguous new payable parties but keeps known payable records maintainable',()=>{
    expect(()=>data.saveOrderCost(orderId,'',draft({direction:'应付',partyId:'PT-00027'}))).toThrow('186')
    const row=data.state.costs.find(row=>row.id==='COST-23-DEMO-4')
    data.saveOrderCost(orderId,row.id,{...row,unitPrice:'180'});expect(row.amount).toBe(1800)
    expect(()=>data.saveOrderCost(orderId,row.id,{...row,partyId:'PT-00031'})).toThrow('186')
    data.submitOrderCosts([row.id]);expect(row.status).toBe('已提交')
  })
  it('inherits original spot FX into a new adjustment and bounds free-text fields',()=>{
    const source=data.state.costs.find(row=>row.id==='COST-23-DEMO-5')
    Object.assign(source,{currency:'USD',spotRate:'7.1000',agreedRate:'7.1',rateId:'FX-DEMO-003',createdAt:'2026-08-08 09:00:00'})
    const row=data.saveCostAdjustment(source.id,'',{...draft({currency:'USD',agreedRate:'7.1'}),responsibleId:'service'})
    expect(row.spotRate).toBe('7.1000');expect(row.rateId).toBe('FX-DEMO-003')
    expect(()=>data.saveOrderCost(orderId,'',draft({remark:'文'.repeat(201)}))).toThrow('200')
    data.selectWorkbenchPersona('supervisor');expect(()=>data.reviewOrderCosts(['COST-23-DEMO-2'],true,{orderRemark:'文'.repeat(201)})).toThrow('200')
  })
})
