const { chromium, expect } = require(process.env.PLAYWRIGHT_TEST_PATH || 'playwright/test')
const { mkdirSync, readFileSync } = require('node:fs')
const { join } = require('node:path')
const output = join(process.cwd(), 'test-results', 'chapter24')
mkdirSync(output, { recursive: true })

;(async () => {
  const browser = await chromium.launch({ headless: true })
  const page = await browser.newPage({ viewport: { width:1440, height:1000 } })
  const errors=[]
  page.on('pageerror',error=>errors.push(error.message))
  page.on('console',message=>{if(message.type()==='error')errors.push(message.text())})
  const rowWith = text => page.locator('.el-table__row').filter({hasText:text})
  async function select(name,value) {
    const input=page.getByRole('combobox',{name,exact:true})
    await page.locator('.el-select').filter({has:input}).click()
    const id=await input.getAttribute('aria-controls')
    await page.locator(`[id="${id}"]`).getByRole('option',{name:value,exact:true}).click()
    await expect(page.locator(`[id="${id}"]`)).toBeHidden()
  }
  async function role(value) {
    await page.getByRole('button',{name:'切换演示角色',exact:true}).click()
    await select('演示角色',value)
    await page.getByRole('button',{name:'切换角色',exact:true}).click()
  }
  async function confirm() { await page.locator('.el-message-box').getByRole('button',{name:'确认',exact:true}).click() }
  async function tab(name) { await page.getByRole('tab',{name,exact:true}).click() }
  async function queryParty(value) {
    await page.getByRole('textbox',{name:'查询结算单位',exact:true}).fill(value)
    await page.getByRole('button',{name:'查询',exact:true}).click()
  }
  async function noOverflow(width) {
    await page.setViewportSize({width,height:1000})
    await expect.poll(()=>page.locator('.workspace').evaluate(el=>el.getBoundingClientRect().left)).toBe(width>900?224:0)
    await expect(page.locator('.el-message-box')).toBeHidden()
    await expect.poll(()=>page.evaluate(()=>document.documentElement.scrollWidth)).toBeLessThanOrEqual(width)
  }
  try {
    await page.goto((process.env.PROTOTYPE_URL||'http://localhost:10530')+'/#/finance/reconciliation')
    await expect(page.getByRole('heading',{name:'对账管理',exact:true})).toBeVisible()
    await expect(rowWith('BL26090700001')).toHaveCount(1)
    await expect(page.getByRole('button',{name:'确认',exact:true})).toHaveCount(0)
    await noOverflow(1440)
    await page.screenshot({path:join(output,'01-admin-list.png')})
    await role('空运客服 · 周倩')

    // Complete an existing chapter23 cost through both stages in the same browser session.
    await page.evaluate(()=>{location.hash='/finance/costs'})
    await rowWith('FINDEMO260901').getByRole('button',{name:'成本编辑',exact:true}).click()
    await rowWith('新建').locator('.el-checkbox').click()
    await page.getByRole('button',{name:'提交审批',exact:true}).click();await confirm()
    await page.getByRole('button',{name:'返回列表',exact:true}).click()
    await role('空运客服主管 · 周倩');await tab('成本审批')
    await rowWith('FINDEMO260901').getByRole('button',{name:'审批',exact:true}).click()
    await rowWith('应收').locator('.el-checkbox').click()
    await page.getByRole('button',{name:'审批通过',exact:true}).click();await confirm()
    await role('财务会计 · 财务会计演示员')
    await page.locator('.el-table__row').filter({hasText:'1,000.00'}).locator('.el-checkbox').click()
    await page.getByRole('button',{name:'审批通过',exact:true}).click();await confirm()
    await role('空运客服 · 周倩')
    await page.getByRole('button',{name:'进入对账',exact:true}).click()
    await expect(page.locator('[aria-label="对账明细"] .el-table__row')).toHaveCount(5)

    await page.getByRole('button',{name:'按查询条件创建',exact:true}).click()
    await expect(page.getByRole('alert').filter({hasText:'只有相同结算单位'})).toBeVisible()
    await queryParty('启航跨境贸易')
    await expect(page.locator('[aria-label="对账明细"] .el-table__row')).toHaveCount(4)
    await page.getByRole('textbox',{name:'查询结算单位',exact:true}).fill('尚未提交的筛选')
    await expect(page.locator('[aria-label="对账明细"] .el-table__row')).toHaveCount(4)
    await page.getByRole('button',{name:'按查询条件创建',exact:true}).click()
    await expect(page.getByRole('heading',{name:'新建应收对账单',exact:true})).toBeVisible()
    await expect(page.getByLabel('分币种合计')).toContainText('4,000.00')
    await expect(page.getByLabel('分币种合计')).toContainText('200.00')
    await page.getByRole('textbox',{name:'对账单备注',exact:true}).fill('对方核对中，合成演示')
    const bytes=Buffer.from('chapter24 attachment\n=quoted,"text"\n')
    await page.locator('input[type=file]').setInputFiles({name:'reconciliation.txt',mimeType:'text/plain',buffer:bytes})
    await expect(page.getByText(/reconciliation.txt/)).toBeVisible()
    await page.locator('input[type=file]').setInputFiles({name:'rejected.html',mimeType:'text/html',buffer:Buffer.from('<p>not accepted</p>')})
    await expect(page.getByText(/其他文档格式待确认/)).toBeVisible()
    await expect(page.getByText(/rejected.html/)).toHaveCount(0)
    await page.getByRole('button',{name:'返回列表',exact:true}).first().click()
    await page.getByRole('button',{name:'取消',exact:true}).click()
    await expect(page.getByRole('textbox',{name:'对账单备注',exact:true})).toHaveValue('对方核对中，合成演示')
    await noOverflow(820)
    await expect(page.locator('.el-message')).toHaveCount(0)
    await page.screenshot({path:join(output,'02-draft-tablet.png'),fullPage:true})
    await noOverflow(1440)
    await page.getByRole('button',{name:'保存',exact:true}).click()
    await page.getByRole('button',{name:'取消',exact:true}).click()
    await expect(page.getByRole('heading',{name:'新建应收对账单',exact:true})).toBeVisible()
    await page.getByRole('button',{name:'保存',exact:true}).click();await confirm()
    await expect(page.locator('[aria-label="对账明细"] .el-table__row')).toHaveCount(1)
    await tab('对账单列表')
    const saved=rowWith('BL26090800001')
    await expect(saved).toContainText('新建')
    await expect(saved.getByRole('button',{name:'删除',exact:true})).toBeDisabled()
    await expect(saved.getByRole('button',{name:'邮件',exact:true})).toBeDisabled()
    await saved.getByRole('button',{name:'确认',exact:true}).click();await confirm()
    await expect(saved).toContainText('已确认')
    await saved.getByRole('button',{name:'查看',exact:true}).click()
    await expect(page.getByRole('heading',{name:'应收对账单详情',exact:true})).toBeVisible()
    await expect(page.getByText('对方核对中，合成演示',{exact:true})).toBeVisible()
    const fileDownload=page.waitForEvent('download')
    await page.getByRole('button',{name:'下载附件',exact:true}).click()
    const attachment=await fileDownload;await attachment.saveAs(join(output,attachment.suggestedFilename()))
    expect(readFileSync(join(output,'reconciliation.txt'))).toEqual(bytes)
    await page.screenshot({path:join(output,'03-confirmed-detail.png'),fullPage:true})
    await page.getByRole('button',{name:'返回列表',exact:true}).first().click()
    await tab('对账单明细列表')
    await page.getByRole('textbox',{name:'查询对账单号（精确）',exact:true}).fill('26090800001')
    await page.getByRole('button',{name:'查询',exact:true}).click()
    await expect(page.getByRole('button',{name:'导出查询结果',exact:true})).toBeDisabled()
    await page.getByRole('textbox',{name:'查询对账单号（精确）',exact:true}).fill('BL26090800001')
    await page.getByRole('button',{name:'查询',exact:true}).click()
    await expect(page.locator('[aria-label="对账明细"] .el-table__row')).toHaveCount(4)
    const exportDownload=page.waitForEvent('download')
    await page.getByRole('button',{name:'导出查询结果',exact:true}).click()
    const exported=await exportDownload;await exported.saveAs(join(output,exported.suggestedFilename()))
    const csv=readFileSync(join(output,exported.suggestedFilename()),'utf8')
    expect(csv.charCodeAt(0)).toBe(0xFEFF);expect(csv).toContain('"1000"');expect(csv).toContain('"USD"')

    await page.locator('.el-radio-button').filter({hasText:'应付对账单'}).click()
    await tab('待对账列表')
    await page.locator('[aria-label="对账明细"] .el-table__row .el-checkbox').click()
    await page.getByRole('button',{name:'按勾选创建',exact:true}).click()
    await expect(page.getByLabel('分币种合计')).toContainText('800.00')
    await page.getByRole('button',{name:'保存并确认',exact:true}).click();await confirm()
    await expect(page.locator('[aria-label="对账明细"] .el-table__row')).toHaveCount(0)
    await tab('对账单列表');await expect(rowWith('BL26090800002')).toContainText('已确认')
    await role('超级管理员 · 演示管理员')
    await rowWith('BL26090800002').getByRole('button',{name:'查看',exact:true}).click()
    await noOverflow(390)
    await expect(page.getByRole('button',{name:'保存并确认',exact:true})).toHaveCount(0)
    await expect(page.locator('.el-message')).toHaveCount(0)
    await expect(page.getByRole('heading',{name:'应付对账单详情',exact:true})).toBeVisible()
    await expect(page.getByText('BL26090800002',{exact:true})).toBeVisible()
    await page.screenshot({path:join(output,'04-readonly-mobile.png'),fullPage:true})
    expect(errors).toEqual([])
    console.log('GJ-024 browser passed: chapter23 approvals -> AR multi-currency query grouping -> save/confirm/export; AP selected save-confirm; real attachment; read-only admin; desktop/tablet/mobile.')
  } catch(error) {
    await page.screenshot({path:join(output,'failure.png'),fullPage:true})
    throw error
  } finally { await browser.close() }
})().catch(error=>{console.error(error);process.exitCode=1})
